<script>
	// Generated by ../asciiArt from the source photographs there.
	import AsciiShip from '$lib/components/AsciiShip.svelte';
	import Placeholder from '$lib/components/Placeholder.svelte';
	import { fleet } from '$lib/containers.js';
	import { gridArea } from '$lib/grid.js';
	import { server } from '$lib/server.svelte.js';

	/* The readings each row is read across, in the order the row below writes
	   them: name, state, then a used/limit pair per resource, then uptime. */
	const COLUMNS = [
		'Container',
		'Status',
		'CPU',
		'CPU limit',
		'Memory',
		'Memory limit',
		'Uptime'
	];

	/* The containers as the fleet and its slots, both already worked out. */
	let containers = $derived(fleet(server.snapshot?.containers.items));
</script>

<svelte:head>
	<title>Containers — Server — Joshua Smith</title>
</svelte:head>

<div class="grid">
	<!-- Decorative: the page is named by its heading, and the art is thousands
	     of digits to a screen reader. -->
	<div class="box ship-box" aria-hidden="true">
		<div class="ship"><AsciiShip /></div>
	</div>

	<div class="box" style={gridArea({ col: 1, row: 2, w: 4, h: 3 })}>
		{#if containers.slots.length}
			<div class="container-shell">
				<!-- One row a container, one column a reading: the names of the readings
				     are the header, so no row has to repeat them. Scrolls sideways rather
				     than reflowing, because a row read across is the whole point of it. -->
				<div class="fleet">
					<table>
						<thead>
							<tr>
								{#each COLUMNS as column (column)}
									<th class="eyebrow" scope="col">{column}</th>
								{/each}
							</tr>
						</thead>

						<tbody>
							{#each containers.slots as slot (slot.name)}
								<tr>
									<!-- The name docker knows it by, set as the literal it is. -->
									<th class="name" scope="row">{slot.name}</th>
									<td class="state" class:warning={!slot.healthy}>
										<i aria-hidden="true"></i>{slot.status}
									</td>

									<!-- What it is using of what it was given, in that resource's own
									     colour: the reading with the share it comes to under it, then
									     the allowance that share is measured against. -->
									{#each slot.resources as resource (resource.id)}
										<td class="usage" style:color={resource.tone}>
											{resource.value}
											<i class="resource-bar"><i style:width="{resource.fill}%"></i></i>
										</td>
										<td class="limit">{resource.limit}</td>
									{/each}

									<td>{slot.uptime}</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</div>
		{:else}
			<Placeholder note="no container data" lines={6} />
		{/if}
	</div>

	{#each Array(3) as _, i (i)}
		<div class="box"><Placeholder note="—" lines={6} /></div>
	{/each}
</div>

<style>
	/* Not this ship's own width (166) but the width every other piece on the
	   site is drawn at, so a digit here is the same size as a digit anywhere
	   else. The ship is wider than the cell it sits in and is cropped by
	   .ship-box below rather than shrunk to fit. */
	.ship {
		--cols: 166;

		container-type: inline-size;
		margin-bottom: 0.75rem;
	}

	/* Sized to the box it stands in: a character grid has exactly one size, so
	   the font size is what scales the picture. --cols above is how many
	   characters wide the art is and JetBrains Mono advances 0.6021em per
	   character, so dividing the container's width by that span gives the cell
	   size that fills it exactly.

	   Scoped here rather than shared in app.css on purpose: the generated art
	   component carries its own `.ascii-art pre { font-size: 6px }`, and only a
	   rule with this one's specificity beats it.

	   The line height is rounded to whole device pixels because baselines are
	   painted on them — a fractional pitch comes out as a 7, 7, 7, 6 rhythm and
	   bands the picture. */
	.ship :global(pre) {
		font-size: calc(100cqw / (var(--cols) * 0.6021));
		line-height: round(0.72em, var(--device-px, 1px));
	}

	/* Black rather than the surface every other box wears: the art is a picture
	   rather than a chart, and reads as one set against the same black the
	   overview's title stands on, not the page's own near-black surface. */
	.ship-box {
		overflow: hidden;
		background: #000;
	}

	/* Bleeds the table out to the edges of the box that holds it, cancelling
	   that box's own padding on three sides — .fleet's overflow-x is what
	   actually keeps the table's width from pushing the box (or the page
	   around it) wider than its column, so nothing here has to. */
	.container-shell {
		margin-inline: calc(-1 * var(--pad));
		margin-bottom: calc(-1 * var(--pad));
	}

	.name {
		color: var(--color-foreground);
	}

	/* A square of the state's own colour, and the word beside it — the colour is
	   never the only thing saying which way a row reads. */
	.state {
		color: var(--mint);
		text-transform: capitalize;
	}

	.state i {
		display: inline-block;
		width: 0.45rem;
		height: 0.45rem;
		margin-right: 0.5rem;
		background: currentcolor;
	}

	/* The allowance the reading beside it is drawn against, set back from it: the
	   number that moves is the one worth reading down the column. */
	.limit {
		color: var(--text-dim);
	}

	/* Wide enough that the share under the reading is a bar rather than a mark. */
	.usage {
		min-width: 5rem;
	}

	/* Under the reading, the width of the cell it is in. */
	.resource-bar {
		display: block;
		height: 2px;
		margin-top: 0.4rem;
		background: var(--color-border);
	}

	.resource-bar i {
		display: block;
		height: 100%;
		min-width: 0;
		background: currentcolor;
	}

	td.state.warning {
		color: var(--coral);
	}
</style>
