<script>
	// Generated by ../asciiArt from the source photographs there.
	import AsciiShip from '$lib/components/AsciiShip.svelte';
	import Placeholder from '$lib/components/Placeholder.svelte';
	import { fleet } from '$lib/containers.js';
	import { gridArea } from '$lib/grid.js';
	import { server } from '$lib/server.svelte.js';

	/* Order matches what each row below writes: name, state, used/limit per resource, uptime. */
	const COLUMNS = [
		'Container',
		'Status',
		'CPU',
		'CPU limit',
		'Memory',
		'Memory limit',
		'Uptime'
	];

	/* The containers as the fleet and its slots, both already worked out. */
	let containers = $derived(fleet(server.snapshot?.containers.items));
</script>

<svelte:head>
	<title>Containers — Server — Joshua Smith</title>
</svelte:head>

<div class="grid">
	<!-- Decorative — the page heading names it, this is thousands of digits to a screen reader. -->
	<div class="box ship-box" aria-hidden="true">
		<div class="ship"><AsciiShip /></div>
	</div>

	<div class="box" style={gridArea({ col: 1, row: 2, w: 4, h: 3 })}>
		{#if containers.slots.length}
			<div class="container-shell">
				<!-- One row per container, scrolls sideways rather than reflowing — a row read across is the point. -->
				<div class="fleet">
					<table>
						<thead>
							<tr>
								{#each COLUMNS as column (column)}
									<th class="eyebrow" scope="col">{column}</th>
								{/each}
							</tr>
						</thead>

						<tbody>
							{#each containers.slots as slot (slot.name)}
								<tr>
									<!-- The name docker knows it by, set as the literal it is. -->
									<th class="name" scope="row">{slot.name}</th>
									<td class="state" class:warning={!slot.healthy}>
										<i aria-hidden="true"></i>{slot.status}
									</td>

									<!-- Usage, then its share as a bar, then the limit it's measured against — each in the resource's own colour. -->
									{#each slot.resources as resource (resource.id)}
										<td class="usage" style:color={resource.tone}>
											{resource.value}
											<i class="resource-bar"><i style:width="{resource.fill}%"></i></i>
										</td>
										<td class="limit">{resource.limit}</td>
									{/each}

									<td>{slot.uptime}</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</div>
		{:else}
			<Placeholder note="no container data" lines={6} />
		{/if}
	</div>

</div>

<style>
	/* Site's shared digit width, not the ship's own 166 — cropped by .ship-box rather than shrunk to fit. */
	.ship {
		--cols: 166;

		container-type: inline-size;
		margin-bottom: 0.75rem;
	}

	/* Font-size is the only knob for a character grid — --cols chars at 0.6021em
	   each, divided into the container width, fills it exactly. Scoped here (not
	   app.css) to out-specificity the generated component's own `font-size: 6px`.
	   Line-height rounded to device pixels, or fractional baselines band the picture. */
	.ship :global(pre) {
		font-size: calc(100cqw / (var(--cols) * 0.6021));
		line-height: round(0.72em, var(--device-px, 1px));
	}

	/* Black, not the usual surface — a picture, not a chart, matching the overview title's black rather than the page surface. */
	.ship-box {
		overflow: hidden;
		background: #000;
	}

	/* Bleeds the table to the box's edges by cancelling padding on three sides. .fleet's overflow-x keeps it from widening the page. */
	.container-shell {
		margin-inline: calc(-1 * var(--pad));
		margin-bottom: calc(-1 * var(--pad));
	}

	.name {
		color: var(--color-foreground);
	}

	/* Colour square + word — colour is never the only signal. */
	.state {
		color: var(--mint);
		text-transform: capitalize;
	}

	.state i {
		display: inline-block;
		width: 0.45rem;
		height: 0.45rem;
		margin-right: 0.5rem;
		background: currentcolor;
	}

	/* Set back — the number that moves is the one worth reading down the column. */
	.limit {
		color: var(--text-dim);
	}

	/* Wide enough that the share under the reading is a bar rather than a mark. */
	.usage {
		min-width: 5rem;
	}

	/* Under the reading, the width of the cell it is in. */
	.resource-bar {
		display: block;
		height: 2px;
		margin-top: 0.4rem;
		background: var(--color-border);
	}

	.resource-bar i {
		display: block;
		height: 100%;
		min-width: 0;
		background: currentcolor;
	}

	td.state.warning {
		color: var(--coral);
	}
</style>
