<script>
	// Generated by ../asciiArt: `make site` there rewrites AsciiAstronaut.svelte.
	import AsciiAstronaut from '$lib/components/AsciiAstronaut.svelte';
	import ToolPills from '$lib/components/ToolPills.svelte';
	import ActionLink from '$lib/components/ActionLink.svelte';

	/* The stops on the rail, most recent first. `points` is what was actually
	   done in that stretch; a stop without any is a single line of prose. */
	const MILESTONES = [
		{
			period: '2024 — Present',
			title: 'Graduate Engineer, AWE',
			points: [
				{
					text: 'Signal-processing pipeline synchronising 9 distributed sensors to microsecond precision — denoising, unsupervised anomaly detection, waveform clustering and TDOA localisation.',
					tools: ['Linux', 'Slurm', 'Git', 'Python', 'scikit-learn', 'Plotly', 'NumPy']
				},
				{
					text: 'Onboard navigation system: 580 m median accuracy at 700 km range against a 7.5 km/s target, 4-second end-to-end latency, inside 8 GB of RAM on a consumer CPU.',
					tools: ['MATLAB']
				},
				{
					text: 'Multi-objective optimisation by surrogate modelling: 150,000 function evaluations down to 20,000, CUDA for a 26x cut in wall time, deployed company-wide.',
					tools: ['Python', 'Git', 'Slurm', 'CUDA', 'Pandas', 'Linux']
				}
			]
		},
		{
			period: '2020 — 2023',
			title: 'BEng Engineering Mathematics',
			detail: 'University of Bristol, 2:1. Modelling, statistics and scientific computing.'
		}
	];
</script>

<section id="about" class="page about">
	<section class="surface-box journey">
		<!-- Decorative: the stops beside it carry the meaning, and the art is
		     thousands of digits to a screen reader. -->
		<div class="visual" aria-hidden="true">
			<div class="bracket-frame"><div class="portrait"><AsciiAstronaut /></div></div>
		</div>

		<div class="timeline">
			<div class="timeline-head">
				<h2 class="section-title">My journey</h2>
				<ActionLink
					variant="cta"
					direction="download"
					href="/cv.pdf"
					download="joshua-smith-cv.pdf"
					class="cv"
				>
					Download CV
				</ActionLink>
			</div>
			{#each MILESTONES as { period, title, detail, points } (title)}
				<div class="milestone">
					<p class="period">{period}</p>
					<h3 class="title">{title}</h3>
					{#if detail}<p class="detail">{detail}</p>{/if}
					{#if points}
						<ul>
							{#each points as { text, tools } (text)}
								<li>
									{text}
									<ToolPills {tools} />
								</li>
							{/each}
						</ul>
					{/if}
				</div>
			{/each}
		</div>
	</section>
</section>

<style>
	/* The section is its two boxes and the air between them: laid out across
	   rather than read down, so it takes the dashboard's width rather than a
	   column of prose. */
	.about {
		gap: clamp(0.75rem, 1.5vh, 1.25rem);
	}

	/* --- my journey ----------------------------------------------------- */

	/* The visual on the left, the stops on the right and with twice the room:
	   the rail is what this box is for, and it was reading the narrower of the
	   two. */
	.journey {
		display: grid;
		grid-template-columns: minmax(0, 1fr) minmax(0, 2fr);
	}

	/* The two halves are divided by a rule run wall to wall, which is what the
	   negative margin and the padding put back are for. */
	.visual {
		display: grid;
		align-content: center;
		margin: calc(-1 * var(--pad)) 0 calc(-1 * var(--pad)) calc(-1 * var(--pad));
		padding: var(--pad);
		border-right: var(--rule);
	}

	/* A character grid has one size — how big one cell is — so the art is sized by
	   setting that from the box it stands in: --cols is its column count times the
	   0.6021em JetBrains Mono advances per character, which makes the art span this
	   half of the box exactly. See ../asciiArt's Makefile for how the 73 was
	   measured.

	   Scoped here rather than shared in app.css on purpose: the generated art
	   component carries its own `.ascii-art pre { font-size: 6px }`, and only a rule
	   with this one's specificity beats it.

	   The line height is rounded to whole device pixels because baselines are
	   painted on them — a fractional pitch comes out as a 7, 7, 7, 6 rhythm and
	   bands the picture. */
	.portrait {
		/* How many characters wide the astronaut is. */
		--cols: 73;

		container-type: inline-size;

		/* The art is a few thousand one-character spans, and inline layout over
		   that many boxes is not cheap. Anything that changes the height of a
		   section above this one — the projects accordion opening a fold — makes
		   the page below it reflow, and this was most of what got reflowed. Off
		   screen it is skipped entirely instead. Safe to contain: the <pre> is
		   sized by this container (100cqw below), so nothing outside measures
		   the art to size itself. `auto` remembers the last rendered height, so
		   the scrollbar does not jump as it comes back into view. */
		content-visibility: auto;
		contain-intrinsic-size: auto 1px;
	}

	.portrait :global(pre) {
		font-size: calc(100cqw / (var(--cols) * 0.6021));
		line-height: round(0.72em, var(--device-px, 1px));
	}

	/* The rail the milestones hang off, in the dots every measuring line on the
	   site is drawn with. */
	.timeline {
		display: grid;
		gap: 1rem;
		align-content: start;
		padding-left: var(--pad);
	}

	/* The eyebrow and the CV link share a line: the one other thing worth doing
	   at the top of the rail, set in the same voice as the hero's own cta. */
	.timeline-head {
		display: flex;
		flex-wrap: wrap;
		align-items: baseline;
		justify-content: space-between;
		gap: 0.5rem;
	}

	/* ActionLink's own .cta size is a step up from this row's own scale — the
	   two figures the rest of its look (mint, mono, nudge) comes from ActionLink
	   still hold. */
	:global(.cv) {
		font-size: var(--fs-xs);
		letter-spacing: 0.12em;
	}

	.milestone {
		position: relative;
		padding-left: 1.5rem;
		color: var(--color-border);
		background-image: var(--dot-column);
		background-position: 0.2rem 0;
		background-repeat: no-repeat;
		background-size: 1px 100%;
	}

	/* When it was, what it was, and what it came to. The rail is drawn in the
	   border colour, so the type on it sets its own back. */
	.period {
		margin: 0;
		color: var(--mint);
		font-family: var(--font-mono);
		font-size: var(--fs-xs);
		letter-spacing: 0.12em;
	}

	.title {
		margin: 0.3rem 0 0;
		color: var(--color-foreground);
		font-size: var(--fs-base);
		font-weight: 700;
	}

	.detail,
	.milestone li {
		color: var(--text-dim);
		font-size: var(--fs-sm);
		line-height: 1.7;
	}

	.detail {
		margin: 0.3rem 0 0;
	}

	.milestone ul {
		display: grid;
		gap: 0.4rem;
		margin: 0.4rem 0 0;
		padding: 0;
		list-style: none;
	}

	/* The mark stands in the gutter rather than indenting the text off it. The
	   pills sit under the line they belong to, standing off it by less than the
	   next point stands off this one — so they read as part of the entry rather
	   than as a row of their own. */
	.milestone li {
		position: relative;
		display: grid;
		gap: 0.45rem;
		padding-left: 0.9rem;
		padding-bottom: 0.35rem;
	}

	.milestone li::before {
		position: absolute;
		left: 0;
		color: var(--mint);
		content: '—';
	}

	/* The stop on the rail, level with the top of the entry beside it. */
	.milestone::before {
		position: absolute;
		top: 0.35rem;
		left: 0;
		width: 0.45rem;
		height: 0.45rem;
		border-radius: 50%;
		background: currentcolor;
		content: '';
	}

	/* --- narrow ---------------------------------------------------------- */

	/* Below this the journey's halves stack rather than standing side by side. */
	@media (max-width: 60rem) {
		.journey {
			grid-template-columns: minmax(0, 1fr);
		}

		/* Stacked, the stops come first and the visual goes under them: it is the
		   decoration, and on one column the reading order is the order. */
		.visual {
			order: 1;
			margin: 0 calc(-1 * var(--pad)) calc(-1 * var(--pad));
			border-top: var(--rule);
			border-right: 0;
		}

		.timeline {
			padding-left: 0;
			padding-bottom: var(--pad);
		}
	}
</style>
