<script>
	// Generated by ../asciiArt: `make site` there rewrites AsciiAstronaut.svelte.
	import AsciiAstronaut from '$lib/components/AsciiAstronaut.svelte';
	import Logo from '$lib/components/Logo.svelte';
	import Placeholder from '$lib/components/Placeholder.svelte';
	import { brandColors, websites } from '$lib/logos.js';

	/* Three boxes down the page: who I am, what I have done, and what I build
	   with. The work itself is its own page now (routes/projects). Each is a
	   list here and a section below, so the markup stays a shape and the content
	   stays editable in one place.

	   The strip of readings under the intro: the figure, and what it counts. */
	const STATS = [
		['6+', 'Years of Python'],
		['2', 'Years professional experience'],
		['10+', 'Projects delivered'],
		['5', 'Tools built']
	];
	/* The stops on the rail, oldest first. `points` is what was actually done in
	   that stretch; a stop without any is a single line of prose. */
	const MILESTONES = [
		{
			period: '2020 — 2023',
			title: 'BEng Engineering Mathematics',
			detail: 'University of Bristol, 2:1. Modelling, statistics and scientific computing.'
		},
		{
			period: '2024 — Present',
			title: 'Graduate Data Scientist, AWE',
			points: [
				'Signal-processing pipeline synchronising 9 distributed sensors to microsecond precision — denoising, unsupervised anomaly detection, waveform clustering and TDOA localisation.',
				'Onboard navigation system: 580 m median accuracy at 700 km range against a 7.5 km/s target, 4-second end-to-end latency, inside 8 GB of RAM on a consumer CPU.',
				'Multi-objective optimisation by surrogate modelling: 150,000 function evaluations down to 20,000, CUDA for a 26x cut in wall time, deployed company-wide.'
			]
		},
		{
			period: 'The future',
			title: 'Whatever the next hard problem is',
			detail:
				'Continuing to build systems that turn messy data into decisions, and looking for the next one worth working on.'
		}
	];
	/* What I work in, grouped by what each thing is for, and how well — a level
	   from 1 to 4, drawn as that many filled dots and read against the key
	   beside them. */
	const CATEGORIES = [
		[
			'Languages & query',
			[
				['Python', 4],
				['C++', 2],
				['SQL', 2],
				['MATLAB', 4],
				['JavaScript', 2]
			]
		],
		[
			'ML & modelling',
			[
				['PyTorch', 3],
				['TensorFlow', 3],
				['scikit-learn', 4]
			]
		],
		[
			'Data & analytics',
			[
				['NumPy', 4],
				['Pandas', 4],
				['Polars', 3],
				['Plotly', 2]
			]
		],
		[
			'Compute & HPC',
			[
				['CUDA', 2],
				['Slurm', 3],
				['Linux', 3]
			]
		],
		[
			'Tooling',
			[
				['Git', 4],
				['Docker', 3],
				['Svelte', 1]
			]
		]
	];

	/* What a filled dot is worth, most first. */
	const LEVELS = [
		[4, "I'm never getting my life back"],
		[3, 'Hundreds'],
		[2, 'Many'],
		[1, 'Some']
	];
</script>

{#snippet dots(level)}
	<span class="dots" aria-hidden="true">
		{#each { length: 4 }, i (i)}<i class:on={i < level}></i>{/each}
	</span>
{/snippet}

<section id="about" class="page about">
	<section class="surface-box hero">
		<div class="intro">
			<h2 class="eyebrow">About me</h2>
			<p class="headline">Turning Data<br />Into Intelligence</p>

			<p class="lede">
				I'm a data scientist and AI engineer focused on building intelligent systems that
				solve real world problems. My work sits at the intersection of data, algorithms
				and human impact.
			</p>

			<div class="cta">
				<a href="#projects"><span aria-hidden="true">&gt;</span> View my work</a>
			</div>

			<!-- The strip along the foot: a figure, what it counts, and its trend. -->
			<div class="stats">
				{#each STATS as [figure, label] (label)}
					<div class="stat">
						<strong>{figure}</strong>
						<span class="eyebrow">{label}</span>
						<!-- The trend under each: nothing to plot yet. -->
						<Placeholder note="" lines={1} />
					</div>
				{/each}
			</div>
		</div>

		<!-- Decorative: the headline beside it says what the page is, and the art is
		     thousands of digits to a screen reader. -->
		<div class="frame">
			<div class="portrait" aria-hidden="true"><AsciiAstronaut /></div>
		</div>
	</section>

	<section class="surface-box journey">
		<div class="timeline">
			<h2 class="eyebrow">My journey</h2>
			{#each MILESTONES as { period, title, detail, points } (title)}
				<div class="milestone">
					<p class="period">{period}</p>
					<p class="title">{title}</p>
					{#if detail}<p class="detail">{detail}</p>{/if}
					{#if points}
						<ul>
							{#each points as point (point)}<li>{point}</li>{/each}
						</ul>
					{/if}
				</div>
			{/each}
		</div>

		<div class="visual"><Placeholder note="journey visual" lines={16} /></div>
	</section>

	<section class="surface-box tools">
		<div class="tools-head">
			<h2 class="eyebrow">Tools &amp; technicalities</h2>
			<p class="strap">
				Technologies I work with to build reliable, scalable and intelligent systems.
			</p>
		</div>

		<div class="tools-body">
			<div class="rows">
				{#each CATEGORIES as [category, tools] (category)}
					<div class="tool-row">
						<h3 class="category">{category}</h3>

						<ul class="chips">
							{#each tools as [tool, level] (tool)}
								<li style="--brand: {brandColors[tool] ?? 'currentcolor'}">
									{#if websites[tool]}
										<a href={websites[tool]} target="_blank" rel="noopener noreferrer">
											<Logo name={tool} /> {tool} {@render dots(level)}
										</a>
									{:else}
										<Logo name={tool} /> {tool} {@render dots(level)}
									{/if}
								</li>
							{/each}
						</ul>
					</div>
				{/each}
			</div>

			<aside class="key">
				<h3 class="eyebrow">Hours spent swearing at it</h3>

				<dl>
					{#each LEVELS as [level, name] (name)}
						<div><dt>{@render dots(level)}</dt><dd>{name}</dd></div>
					{/each}
				</dl>

				<div class="art"><Placeholder note="ascii" lines={5} /></div>
			</aside>
		</div>
	</section>
</section>

<style>
	/* The page is the four boxes and the air between them: laid out across
	   rather than read down, so it takes the dashboard's width rather than a
	   column of prose. */
	.about {
		gap: clamp(0.75rem, 1.5vh, 1.25rem);
	}

	/* --- about me ------------------------------------------------------- */

	.hero {
		display: grid;
		grid-template-columns: minmax(0, 1fr) minmax(0, 1.1fr);
		gap: clamp(1.5rem, 4vw, 3rem);
	}

	/* Five rows, the last of them the slack: the strip of readings is pushed to
	   the foot of the column so it lands level with the bottom of the portrait
	   beside it, however short the copy above turns out to be. */
	.intro {
		display: grid;
		grid-template-rows: repeat(4, auto) minmax(0, 1fr);
		gap: clamp(1rem, 2vh, 1.5rem);
	}

	/* The page's own headline: the one piece of type here set as large as the
	   name on the landing page, and the only thing in the box at full strength. */
	.headline {
		margin: 0;
		color: var(--color-foreground);
		font-size: clamp(2rem, 4vw, 3.25rem);
		font-weight: 700;
		letter-spacing: -0.04em;
		line-height: 1.08;
	}

	/* Set in the mono face the readings elsewhere on the site are, which is what
	   keeps a paragraph of prose reading as part of a dashboard. */
	.lede {
		margin: 0;
		max-width: 46ch;
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.85rem;
		line-height: 1.9;
	}

	/* A button is a button's width, not the column's. */
	.cta {
		width: fit-content;
	}

	.cta a {
		display: block;
		padding: 0.7rem 1.1rem;
		border: 1px solid currentcolor;
		border-radius: 0.2rem;
		background: none;
		color: var(--mint);
		font-family: var(--font-mono);
		font-size: 0.72rem;
		letter-spacing: 0.18em;
		text-transform: uppercase;
		text-decoration: none;
		cursor: pointer;
		transition: background-color 160ms ease;
	}

	.cta a:hover,
	.cta a:focus-visible {
		background: color-mix(in srgb, var(--mint) 12%, transparent);
	}

	/* Four readings across the foot, ruled apart, the last of them pushed down to
	   the bottom of the column so it lands level with the foot of the portrait. */
	.stats {
		display: grid;
		grid-template-columns: repeat(4, minmax(0, 1fr));
		gap: 0.35rem 1rem;
		align-content: end;
		margin-top: auto;
	}

	/* Three rows, the middle one taking the slack: the labels run to different
	   lengths, and the trends under them still have to sit on one line. */
	.stat {
		display: grid;
		grid-template-rows: auto minmax(0, 1fr) auto;
		gap: 0.35rem;
	}

	/* The figure in the colour a reading is given everywhere else on the site, the
	   line under it in the same small caps as every other label. */
	.stat strong {
		color: var(--mint);
		font-family: var(--font-mono);
		font-size: clamp(1.5rem, 2.4vw, 2rem);
		font-weight: 700;
		letter-spacing: -0.02em;
		line-height: 1;
	}

	.stat .eyebrow {
		line-height: 1.5;
	}

	.stat + .stat {
		padding-left: 1rem;
		border-left: var(--rule);
	}

	/* A character grid has one size -- how big one cell is -- so the art is sized
	   by setting that from the box it stands in: --cols is its column count times
	   the 0.6021em JetBrains Mono advances per character, which makes the art span
	   this box exactly. The box is a share of the frame rather than the whole of
	   it, and that share is what holds the digits at the size every other piece of
	   art on the site is set at: 73 columns over 66.4% of a 628.67px frame is a
	   5.72px advance, the same as the bull's. See ../asciiArt's Makefile for how
	   the 73 and the 70 rows under it were chosen. */
	.portrait {
		/* How many characters wide the astronaut is. */
		--cols: 73;

		container-type: inline-size;
		width: 66.4%;
		margin-inline: auto;
	}

	/* Sized to the box it stands in: a character grid has exactly one size, so
	   the font size is what scales the picture. --cols above is how many
	   characters wide the art is and JetBrains Mono advances 0.6021em per
	   character, so dividing the container's width by that span gives the cell
	   size that fills it exactly.

	   Scoped here rather than shared in app.css on purpose: the generated art
	   component carries its own `.ascii-art pre { font-size: 6px }`, and only a
	   rule with this one's specificity beats it.

	   The line height is rounded to whole device pixels because baselines are
	   painted on them — a fractional pitch comes out as a 7, 7, 7, 6 rhythm and
	   bands the picture. */
	.portrait :global(pre) {
		font-size: calc(100cqw / (var(--cols) * 0.6021));
		line-height: round(0.72em, var(--device-px, 1px));
	}

	/* The corner brackets the portrait sits in: eight hairlines, two to a corner,
	   drawn as backgrounds rather than elements — the same trick Placeholder draws
	   its dotted edges with. */
	.frame {
		--corner: 1.75rem;
		--edge: linear-gradient(var(--color-border) 0 0);

		display: grid;
		padding: 0.75rem;
		background-image: var(--edge), var(--edge), var(--edge), var(--edge), var(--edge),
			var(--edge), var(--edge), var(--edge);
		background-position: 0 0, 0 0, 100% 0, 100% 0, 0 100%, 0 100%, 100% 100%, 100% 100%;
		background-repeat: no-repeat;
		background-size: var(--corner) 1px, 1px var(--corner), var(--corner) 1px, 1px var(--corner),
			var(--corner) 1px, 1px var(--corner), var(--corner) 1px, 1px var(--corner);
	}

	/* --- my journey ----------------------------------------------------- */

	.journey {
		display: grid;
		grid-template-columns: minmax(0, 1fr) minmax(0, 2fr);
	}

	/* The two halves are divided by a rule run wall to wall, which is what the
	   negative margin and the padding put back are for. */
	.visual {
		display: grid;
		margin: calc(-1 * var(--pad)) calc(-1 * var(--pad)) calc(-1 * var(--pad)) 0;
		padding: var(--pad);
		border-left: var(--rule);
	}

	/* The rail the milestones hang off, in the dots every measuring line on the
	   site is drawn with. */
	.timeline {
		display: grid;
		gap: 1rem;
		align-content: start;
		padding-right: var(--pad);
	}

	.milestone {
		position: relative;
		padding-left: 1.5rem;
		color: var(--color-border);
		background-image: var(--dot-column);
		background-position: 0.2rem 0;
		background-repeat: no-repeat;
		background-size: 1px 100%;
	}

	/* When it was, what it was, and what it came to. The rail is drawn in the
	   border colour, so the type on it sets its own back. */
	.period {
		margin: 0;
		color: var(--mint);
		font-family: var(--font-mono);
		font-size: 0.68rem;
		letter-spacing: 0.12em;
	}

	.title {
		margin: 0.3rem 0 0;
		color: var(--color-foreground);
		font-size: 0.9rem;
		font-weight: 700;
	}

	.detail,
	.milestone li {
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.72rem;
		line-height: 1.7;
	}

	.detail {
		margin: 0.3rem 0 0;
	}

	.milestone ul {
		display: grid;
		gap: 0.4rem;
		margin: 0.4rem 0 0;
		padding: 0;
		list-style: none;
	}

	/* The mark stands in the gutter rather than indenting the text off it. */
	.milestone li {
		position: relative;
		padding-left: 0.9rem;
	}

	.milestone li::before {
		position: absolute;
		left: 0;
		color: var(--mint);
		content: '—';
	}

	/* The stop on the rail, level with the top of the entry beside it. */
	.milestone::before {
		position: absolute;
		top: 0.35rem;
		left: 0;
		width: 0.45rem;
		height: 0.45rem;
		border-radius: 50%;
		background: currentcolor;
		content: '';
	}

	/* --- tools & technicalities ------------------------------------------ */

	.tools .eyebrow {
		display: block;
		margin-bottom: var(--pad);
	}


	/* The heading and the line under it sit on one row, the way the drawing has
	   them: what the section is on the left, what it is for beside it. */
	.tools-head {
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem 2rem;
		align-items: baseline;
		margin-bottom: var(--pad);
	}

	.strap {
		margin: 0;
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.72rem;
	}

	/* The groups take the width; the legend is a fixed column beside them. */
	.tools-body {
		display: grid;
		grid-template-columns: minmax(0, 1fr) 20rem;
		gap: clamp(1.5rem, 3vw, 2.5rem);
	}

	.rows {
		display: grid;
		align-content: start;
	}

	/* A group is a line: what it is called on the left, everything in it across
	   the rest, ruled off from the group under it. */
	.tool-row {
		display: grid;
		grid-template-columns: 14rem minmax(0, 1fr);
		gap: 0rem;
		align-items: center;
		padding: 0.85rem 0;
	}

	.tool-row + .tool-row {
		border-top: var(--rule);
	}

	.category {
		margin: 0;
		font-size: 0.85rem;
		font-weight: 700;
	}

	/* One tool, one pill: its name and how much of it there is. */
	.chips {
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem;
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.chips li {
		position: relative;
		display: flex;
		gap: 0.5rem;
		align-items: center;
		padding: 0.35rem 0.8rem;
		border: 1px solid var(--color-border);
		border-radius: 999px;
		font-family: var(--font-mono);
		font-size: 0.72rem;
	}

	/* `display: contents` lays the icon/name/dots out as if they were direct
	   children of the pill; the `::after` is what actually catches the click,
	   stretched over the whole pill rather than just the text and icon. */
	.chips li > :global(a) {
		display: contents;
		color: inherit;
		text-decoration: none;
	}

	.chips li > :global(a::after) {
		content: '';
		position: absolute;
		inset: 0;
		border-radius: inherit;
	}

	.chips li:has(a):hover {
		border-color: var(--brand);
	}

	.chips li:has(a):hover :global(svg) {
		fill: var(--brand);
	}

	/* The meter: four dots, filled up to the level. Every one of them is hollow
	   until the levels are written, which is what says the ranking is not in yet
	   rather than saying everything is a 0. */
	.dots {
		display: inline-flex;
		gap: 0.22rem;
		align-items: center;
		color: var(--mint);
	}

	.dots i {
		width: 0.38rem;
		height: 0.38rem;
		border: 1px solid currentcolor;
		border-radius: 50%;
	}

	.dots i.on {
		background: currentcolor;
	}

	/* What the dots are worth, in its own box beside them. Not `.legend`: that is
	   the chart key in app.css, whose swatch paints itself in, which would fill
	   every hollow dot in here. */
	.key {
		display: grid;
		align-content: start;
		gap: 0.75rem;
		padding: var(--divide, 1rem);
		border: 1px solid var(--color-border);
		border-radius: 0.35rem;
	}

	.key dl {
		display: grid;
		gap: 0.4rem;
		margin: 0;
	}

	.key dl div {
		display: flex;
		gap: 0.6rem;
		align-items: center;
	}

	.key dd {
		margin: 0;
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.7rem;
		white-space: nowrap;
	}

	/* The art that fills the foot of the box, once there is any. */
	.key .art {
		margin-top: auto;
	}

	/* --- narrow ---------------------------------------------------------- */

	/* Below this nothing holds its columns: the portrait goes under the copy, the
	   journey's halves stack, and the four-across rows become two. */
	@media (max-width: 60rem) {
		.hero,
		.journey {
			grid-template-columns: minmax(0, 1fr);
		}

		.visual {
			margin: 0 calc(-1 * var(--pad)) calc(-1 * var(--pad));
			border-top: var(--rule);
			border-left: 0;
		}

		.timeline {
			padding-right: 0;
			padding-bottom: var(--pad);
		}

		/* The legend has nowhere to stand beside the groups: it goes under them. */
		.tools-body {
			grid-template-columns: minmax(0, 1fr);
		}

		/* And a group's name goes above what is in it rather than beside it. */
		.tool-row {
			grid-template-columns: minmax(0, 1fr);
			gap: 0.6rem;
		}
	}

	@media (max-width: 40rem) {
		.stats {
			grid-template-columns: repeat(2, minmax(0, 1fr));
		}

		.stat:nth-child(odd) {
			padding-left: 0;
			border-left: 0;
		}
	}
</style>
