<script>
	// Generated by ../asciiArt: `make site` there rewrites AsciiRadioDish.svelte.
	import AsciiRadioDish from '$lib/components/AsciiRadioDish.svelte';
	import Logo from '$lib/components/Logo.svelte';
	import ActionLink from '$lib/components/ActionLink.svelte';
	import { PUBLIC_WEB3FORMS_KEY } from '$env/static/public';
	import { ticking } from '$lib/clock.svelte.js';

	/* The clock, kept live rather than stamped at build time. Europe/London
	   carries its own BST/GMT switch -- the formatters below read it straight
	   off Intl's tz database, so there is no manual DST rule to get wrong or
	   forget to flip. */
	const TIME_ZONE = 'Europe/London';
	const timeFormat = new Intl.DateTimeFormat('en-GB', {
		timeZone: TIME_ZONE,
		hour: '2-digit',
		minute: '2-digit',
		hour12: false
	});
	const zoneFormat = new Intl.DateTimeFormat('en-GB', {
		timeZone: TIME_ZONE,
		timeZoneName: 'short'
	});
	const offsetFormat = new Intl.DateTimeFormat('en-GB', {
		timeZone: TIME_ZONE,
		timeZoneName: 'shortOffset'
	});
	const zonePart = (formatted) => formatted.find((part) => part.type === 'timeZoneName').value;

	/* Every half minute: this shows hours and minutes only, so there is nothing
	   a faster tick could change. */
	const clock = ticking(30_000);

	let localTime = $derived(timeFormat.format(clock.now));
	let localZone = $derived(zonePart(zoneFormat.formatToParts(clock.now)));
	let localOffset = $derived(zonePart(offsetFormat.formatToParts(clock.now)).replace('GMT', 'UTC'));

	/* Where to reach me, in the order I would rather be reached. `icon` is the
	   mark $lib/logos.js draws for that channel. */
	const CHANNELS = [
		{
			key: 'email',
			icon: 'Email',
			label: 'js-195@outlook.com',
			href: 'mailto:js-195@outlook.com'
		},
		{
			key: 'github',
			icon: 'GitHub',
			label: 'github.com/JS195',
			href: 'https://github.com/JS195'
		},
		{
			key: 'linkedin',
			icon: 'LinkedIn',
			label: 'linkedin.com/in/joshua-smith-487846181',
			href: 'https://www.linkedin.com/in/joshua-smith-487846181/'
		},
		{
			key: 'cv',
			icon: 'CV',
			label: 'Download CV',
			href: '/cv.pdf',
			download: 'joshua-smith-cv.pdf'
		}
	];

	/* The form itself, posted straight to Web3Forms from the browser: this site
	   builds to static files, so there's no server route of its own to receive
	   it. The honeypot is a field a real visitor never sees or fills; Web3Forms
	   drops the submission if it comes back non-empty. */
	let name = $state('');
	let email = $state('');
	let message = $state('');
	let honeypot = $state('');
	let status = $state('idle'); // idle | sending | sent | error

	async function sendMessage(event) {
		event.preventDefault();
		status = 'sending';
		try {
			const response = await fetch('https://api.web3forms.com/submit', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
				body: JSON.stringify({
					access_key: PUBLIC_WEB3FORMS_KEY,
					subject: `New message from ${name} via js195.co.uk`,
					name,
					email,
					message,
					botcheck: honeypot
				})
			});
			const result = await response.json();
			if (!result.success) throw new Error(result.message);
			status = 'sent';
			name = '';
			email = '';
			message = '';
		} catch {
			status = 'error';
		}
	}
</script>

<section id="contact" class="page contact">
	<section class="surface-box panel">
		<div class="intro">
			<h2 class="section-title">Contact</h2>

			<p class="headline">What's on your radar?</p>
			<p class="lede">
				Whether it's an opportunity, an interesting problem, or a question: get in contact,
				I'd love to connect.
			</p>

			<p class="clock">
				<span class="dot" aria-hidden="true"></span>
				UK-based · {localTime} {localZone}
				<span class="offset">({localOffset})</span>
			</p>

			<div class="rule"></div>

			<ul class="channels">
				{#each CHANNELS as channel (channel.key)}
					<li>
						<div class="icon"><Logo name={channel.icon} /></div>
						{#if channel.href.startsWith('mailto:')}
							<a class="value" href={channel.href}>{channel.label}</a>
						{:else}
							<ActionLink
								variant="plain"
								direction={channel.download ? 'download' : 'external'}
								href={channel.href}
								download={channel.download}
								class="value"
							>
								{channel.label}
							</ActionLink>
						{/if}
					</li>
				{/each}
			</ul>

			<div class="rule"></div>

			<form onsubmit={sendMessage}>
				<h3 class="eyebrow">Or send a message</h3>

				<!-- Off-screen rather than display:none, which some bots skip filling
				     because it's known to be inert; a real visitor never tabs to it.
				     aria-hidden too: tabindex="-1" only takes it out of tab order, and
				     a screen reader's own browse mode would otherwise still land on an
				     unlabelled text field. -->
				<input
					type="text"
					name="botcheck"
					class="botcheck"
					tabindex="-1"
					aria-hidden="true"
					autocomplete="off"
					bind:value={honeypot}
				/>

				<div class="field">
					<label for="name">Name</label>
					<input id="name" type="text" required autocomplete="name" bind:value={name} />
				</div>

				<div class="field">
					<label for="email">Email</label>
					<input id="email" type="email" required autocomplete="email" bind:value={email} />
				</div>

				<div class="field">
					<label for="message">Message</label>
					<textarea id="message" rows="4" required bind:value={message}></textarea>
				</div>

				<div class="actions">
					<button type="submit" disabled={status === 'sending'}>
						{status === 'sending' ? 'Sending…' : 'Send message'}
					</button>
					<!-- Announced on its own: role="status" plus aria-live so a screen
					     reader reports the result without the visitor having to go
					     looking for it, the way a sighted one can just see the line
					     appear. Polite, not assertive — it waits for a pause rather
					     than cutting off whatever the reader is already doing. -->
					<div role="status" aria-live="polite">
						{#if status === 'sent'}
							<p class="feedback ok">Sent — thanks, I'll get back to you.</p>
						{:else if status === 'error'}
							<p class="feedback err">
								Something went wrong — try again, or email me directly instead.
							</p>
						{/if}
					</div>
				</div>
			</form>
		</div>

		<!-- Decorative: the copy beside it carries the meaning. -->
		<div class="bracket-frame" aria-hidden="true">
			<div class="visual"><AsciiRadioDish /></div>
		</div>
	</section>
</section>

<style>
	.contact {
		gap: clamp(1.5rem, 3vh, 2rem);
	}

	/* The copy and its channels down the left, the form and the dish on the
	   right. The box itself is .surface-box (app.css); this is only how the one
	   box divides. */
	.panel {
		display: grid;
		grid-template-columns: minmax(0, 1fr) minmax(0, 1.9fr);
		gap: clamp(1.5rem, 4vw, 3rem);
	}

	.intro {
		display: grid;
		gap: 1rem;
		align-content: start;
	}

	/* The line under the eyebrow, in the same voice as the hero's tagline: a
	   claim, not a label, so it is set in the body face and bold rather than
	   the mono every reading on the page wears. */
	.headline {
		margin: -0.5rem 0 0;
		color: var(--color-foreground);
		font-size: clamp(1.25rem, 2vw, 1.6rem);
		font-weight: 700;
		letter-spacing: -0.02em;
		line-height: 1.2;
	}

	.lede {
		margin: 0;
		max-width: 62ch;
		color: var(--text-dim);
		font-size: var(--fs-base);
		line-height: 1.6;
	}

	.rule {
		height: 1px;
		margin: 0.5rem 0;
		background: var(--color-border);
	}

	.clock {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		margin: 0;
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: var(--fs-xs);
		letter-spacing: 0.02em;
	}

	.clock .dot {
		width: 0.4rem;
		height: 0.4rem;
		border-radius: 50%;
		background: var(--mint);
		box-shadow: 0 0 0.5rem var(--mint);
	}

	.clock .offset {
		color: var(--text-faint);
	}

	.channels {
		display: grid;
		gap: 0.75rem;
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.channels li {
		display: grid;
		grid-template-columns: 2rem minmax(0, 1fr);
		gap: 0.75rem;
		align-items: center;
	}

	.channels .icon {
		display: grid;
		place-items: center;
		width: 1.35rem;
		height: 1.35rem;
		color: var(--text-dim);
	}

	a.value {
		color: var(--color-foreground);
		font-family: var(--font-mono);
		font-size: var(--fs-sm);
		text-decoration: none;
	}

	a.value:hover {
		text-decoration: underline;
	}

	/* A character grid has one size -- how big one cell is -- so the art is sized
	   by setting that from the box it sits in: 137 columns times the 0.6021em
	   JetBrains Mono advances per character, which spans this box at the bull's
	   own digit size. See ../asciiArt's Makefile for how the 137 was measured. */
	.visual {
		/* How many characters wide the dish is. */
		--cols: 137;

		container-type: inline-size;
		display: grid;

		/* The dish is ~5.7k one-character spans, the largest block of inline
		   layout on the page after the hero. Contact is the last section, so
		   anything above it changing height — the projects accordion opening a
		   fold — reflows all of it. Off screen it is skipped instead. Safe to
		   contain: the <pre> is sized by this container (100cqw below), so
		   nothing outside measures the art to size itself. */
		content-visibility: auto;
		contain-intrinsic-size: auto 1px;
	}

	/* Sized to the box it stands in: a character grid has exactly one size, so
	   the font size is what scales the picture. --cols above is how many
	   characters wide the art is and JetBrains Mono advances 0.6021em per
	   character, so dividing the container's width by that span gives the cell
	   size that fills it exactly.

	   Scoped here rather than shared in app.css on purpose: the generated art
	   component carries its own `.ascii-art pre { font-size: 6px }`, and only a
	   rule with this one's specificity beats it.

	   The line height is rounded to whole device pixels because baselines are
	   painted on them — a fractional pitch comes out as a 7, 7, 7, 6 rhythm and
	   bands the picture. */
	.visual :global(pre) {
		font-size: calc(100cqw / (var(--cols) * 0.6021));
		line-height: round(0.72em, var(--device-px, 1px));
	}

	/* Stacked, not the two-up row the wider standalone box would have room for:
	   this now lives in the .intro column, which is under half the box's width. */
	form {
		display: grid;
		gap: 1rem;
	}

	form .eyebrow {
		display: block;
		margin-bottom: -0.25rem;
	}

	.field {
		display: grid;
		gap: 0.4rem;
	}

	label {
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: var(--fs-xs);
		letter-spacing: 0.1em;
		text-transform: uppercase;
	}

	input,
	textarea {
		border: 1px solid var(--color-border);
		border-radius: var(--radius-control);
		background: var(--color-background);
		color: var(--color-foreground);
		font: inherit;
		font-family: var(--font-mono);
		font-size: var(--fs-sm);
		padding: 0.6rem 0.7rem;
	}

	textarea {
		resize: vertical;
	}

	/* The global :focus-visible ring (app.css) already draws the outline; this
	   is the extra cue on top of it, the same border-colour swap every other
	   focused control on the site gets. */
	input:focus-visible,
	textarea:focus-visible {
		border-color: var(--mint);
	}

	/* Off-screen, not display:none or visibility:hidden -- some spam bots skip
	   filling fields hidden that way but still find this one. */
	.botcheck {
		position: absolute;
		width: 1px;
		height: 1px;
		margin: -1px;
		overflow: hidden;
		clip-path: inset(50%);
		white-space: nowrap;
	}

	.actions {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: 1rem;
	}

	button {
		border: 1px solid var(--mint);
		border-radius: var(--radius-control);
		background: none;
		color: var(--mint);
		font-family: var(--font-mono);
		font-size: var(--fs-xs);
		letter-spacing: 0.18em;
		text-transform: uppercase;
		padding: 0.7rem 1.1rem;
		cursor: pointer;
		transition: background-color 160ms ease;
	}

	button:hover:not(:disabled),
	button:focus-visible:not(:disabled) {
		background: color-mix(in srgb, var(--mint) 12%, transparent);
	}

	button:disabled {
		opacity: 0.6;
		cursor: default;
	}

	.feedback {
		margin: 0;
		font-family: var(--font-mono);
		font-size: var(--fs-sm);
	}

	.feedback.ok {
		color: var(--mint);
	}

	.feedback.err {
		color: var(--coral);
	}

	@media (max-width: 60rem) {
		.panel {
			grid-template-columns: minmax(0, 1fr);
		}
	}
</style>
