<script>
	// Generated by ../asciiArt from the source photographs there.
	import AsciiDish from '$lib/components/AsciiDish.svelte';
	import AsciiShip from '$lib/components/AsciiShip.svelte';
	import Capacity from '$lib/components/Capacity.svelte';
	import Dial from '$lib/components/Dial.svelte';
	import Heatmap from '$lib/components/Heatmap.svelte';
	import Horizon from '$lib/components/Horizon.svelte';
	import MetricRow from '$lib/components/MetricRow.svelte';
	import Panel from '$lib/components/Panel.svelte';
	import Placeholder from '$lib/components/Placeholder.svelte';
	import Spread from '$lib/components/Spread.svelte';
	import Stack from '$lib/components/Stack.svelte';
	import Trace from '$lib/components/Trace.svelte';
	import {
		bytes,
		clockPosition,
		degrees,
		duration,
		microseconds,
		microspan,
		pct,
		ppm,
		rate,
		stamp
	} from '$lib/format.js';
	import { fleet } from '$lib/containers.js';
	import { memoryBands } from '$lib/memory.js';
	import { RANGE, server, watch } from '$lib/server.svelte.js';
	import { bucket, last, mean, outages, summarise } from '$lib/stats.js';
	import { volume } from '$lib/storage.js';
	import { spread } from '$lib/time.js';

	/* Wireframe. CPU and storage are wired up; everything else is a placeholder
	   holding the shape of what goes there. One entry per section of the page and
	   per stop on the rail: a section is a box on the page, its own heading, and
	   its own place in the list. */
	const SECTIONS = [
		{ id: 'uptime', label: 'Uptime' },
		{ id: 'cpu', label: 'CPU' },
		{ id: 'memory', label: 'Memory' },
		{ id: 'storage', label: 'Storage' },
		{ id: 'network', label: 'Network' },
		{ id: 'time', label: 'Time' },
		{ id: 'containers', label: 'Containers' }
	];

	/* The two drives. One entry each: the id is the prefix every one of their
	   series is named with, and the tone is theirs wherever they appear — capacity
	   box, horizon, io lane. */
	const DISKS = [
		{ id: 'nvme', label: 'NVMe', tone: 'var(--violet)' },
		{ id: 'ssd', label: 'SSD', tone: 'var(--azure)' }
	];

	/* Columns in the heatmaps. The series is 24h at five-minute steps, so this is
	   about a quarter-hour a cell — fine enough to see a spike, coarse enough that
	   a cell is still a cell rather than a hairline. */
	const HEAT_COLUMNS = 72;

	$effect(watch);

	let snapshot = $derived(server.snapshot);
	let series = $derived(server.series);
	let month = $derived(server.month);

	/* How the machine's memory is divided, as three shares of the whole. */
	let ram = $derived(memoryBands(series));

	/* Each volume worked out from its own 30-day series: where it is, which way it
	   is going, and when that runs out. The capacity boxes and the horizon are the
	   same objects seen two ways. */
	let volumes = $derived(
		DISKS.map((disk) =>
			volume({
				...disk,
				used: month?.[`${disk.id}UsedBytes`],
				available: month?.[`${disk.id}AvailableBytes`],
				percent: month?.[`${disk.id}Percent`]
			})
		)
	);

	/* The live reading, written the way $lib/format.js writes that quantity — the
	   same spelling the stats and the map key beside it use, so one number is not
	   quoted to two precisions in one box. */
	const reading = (key, format) => format(snapshot?.[key]);

	let current = $state(SECTIONS[0].id);

	/* Which section the rail marks. An observer on the section itself, rather than
	   scroll maths or a document lookup: it is the platform's own answer to "what
	   is on screen". Top-biased margin so the mark flips when a heading reaches
	   the upper third, which is where the eye is, not when the section is half
	   gone. */
	const spy = (id) => (element) => {
		const observer = new IntersectionObserver(
			([entry]) => {
				if (entry.isIntersecting) current = id;
			},
			{ rootMargin: '-20% 0px -70% 0px' }
		);

		observer.observe(element);
		return () => observer.disconnect();
	};

	/* Read and write on each disk, a lane of the pulse map each. The two sit orders
	   of magnitude apart on the same drive, so the map normalises per row — a lane
	   says when that stream was busy, not how it compares to the one under it. The
	   current rate is on the right of each lane for that. */
	let io = $derived(
		DISKS.flatMap(({ id, label, tone }) =>
			['Read', 'Write'].map((direction) => {
				const points = series?.[`${id}${direction}BytesPerSecond`];
				return {
					id: `${label} ${direction.toLowerCase()}`,
					group: label,
					tone,
					now: rate(last(points)),
					cells: bucket(points, HEAT_COLUMNS)
				};
			})
		).filter((lane) => lane.cells.length)
	);

	/* Per-core utilisation as a map: one row a core, one cell a bucket, straight
	   off the same 0-100% scale the traces are drawn against. */
	let cores = $derived(
		Object.entries(series?.cpuPerCorePercent ?? {})
			.sort(([a], [b]) => Number(a) - Number(b))
			.map(([id, points]) => ({
				id: `C${id}`,
				now: pct(last(points)),
				cells: bucket(points, HEAT_COLUMNS)
			}))
	);

	let rx = $derived(series?.networkReceiveBytesPerSecond ?? []);
	let tx = $derived(series?.networkTransmitBytesPerSecond ?? []);
	const ms = (v) => (Number.isFinite(v) ? `${Math.round(v)} ms` : '—');

	/* Availability is read in nines, so it keeps two decimals where pct() would
	   round 99.98% up to a month without an outage in it. */
	const nines = (v) => (Number.isFinite(v) ? `${v.toFixed(2)}%` : '—');

	/* The status series is 1 for a poll the machine answered and 0 for one it did
	   not, so its mean is the share of the window the machine was up.

	   Read off the 24h series and not the 30d one, even though a month is the
	   window worth quoting: the API downsamples the long range to two-hour steps
	   and does not carry the failures through, so every one of its readings is
	   exactly 1 and an outage that plainly happened is not in it. A number that
	   cannot go below 100% is not an availability figure. */
	let statusDay = $derived(series?.status ?? []);
	let availability = $derived(statusDay.length ? mean(statusDay.map((p) => p[1])) * 100 : null);
	let incidents = $derived(outages(statusDay));

	let online = $derived(snapshot?.server === 'online');

	/* The clock, and every source it listens to as a reading with a bound. */
	let clock = $derived(snapshot?.time);
	let offsets = $derived(spread(clock));

	/* Chrony reports the correction needed to reach NTP: a negative correction
	   means this machine is fast. Flip it here so positive reads naturally as
	   PHOBOS ahead and negative as PHOBOS behind. */
	let clockHistory = $derived(
		(series?.timeSystemOffsetSeconds ?? []).map(([time, offset]) => [time, -offset])
	);
	let currentClockOffset = $derived(
		Number.isFinite(clock?.systemOffsetSeconds) ? -clock.systemOffsetSeconds : null
	);
	let clockLimit = $derived.by(() => {
		const greatest = Math.max(50e-6, ...clockHistory.map((point) => Math.abs(point[1])));
		return Math.ceil((greatest * 1.15) / 50e-6) * 50e-6;
	});
	/* The containers as the fleet and its slots, both already written out. */
	let containerFleet = $derived(fleet(snapshot?.containers));
</script>

<svelte:head>
	<title>Server — Joshua Smith</title>
</svelte:head>

{#snippet stub(label, note, lines)}
	<Panel {label}>
		<Placeholder {note} {lines} />
	</Panel>
{/snippet}

{#snippet uptime()}
	<!-- Decorative: the section is named by its heading, and the art is thousands
	     of digits to a screen reader. -->
	<div class="art dish" aria-hidden="true"><AsciiDish /></div>

	<div class="band bleed headline">
		<Panel label="Uptime">
			<!-- How long it has been up is the reading; a machine that is not says so
			     in the word rather than in the colour, which is never the only thing
			     saying which way this reads. -->
			<strong class:down={!online}>{online ? duration(snapshot.uptimeSeconds) : 'Down'}</strong>
		</Panel>

		<Panel label="{RANGE} availability">
			<strong>{nines(availability)}</strong>
		</Panel>

		<Panel label="Incidents">
			<strong class:down={incidents > 0}>{statusDay.length ? incidents : '—'}</strong>
		</Panel>

		<Panel label="Next planned outage">
			<!-- Nothing scheduled is not a reading in the same sense as the three
			     beside it, and is set back so it does not read as one. -->
			<strong class="unknown">—</strong>
		</Panel>
	</div>
{/snippet}

{#snippet cpu()}
	<div class="stack">
		<MetricRow
			label="Usage"
			value={reading('cpuPercent', pct)}
			tone="var(--mint)"
			stats={summarise(series?.cpuPercent, pct)}
		>
			<!-- The key spells out the band the colours cover, since the map is
			     stretched to the range the cores actually ran at. -->
			<Heatmap rows={cores} format={pct} note="no per-core history yet" />
		</MetricRow>

		<MetricRow
			label="Pressure"
			value={reading('cpuPressurePercent', pct)}
			tone="var(--coral)"
			stats={summarise(series?.cpuPressurePercent, pct)}
		>
			<!-- Sustained pressure is the reading that matters rather than any one
			     spike, so the rules are the two levels worth seeing a trace cross. -->
			<Trace
				lines={[{ id: 'pressure', points: series?.cpuPressurePercent, tone: 'var(--coral)' }]}
				domain={[0, 100]}
				format={pct}
				marks={[25, 50]}
			/>
		</MetricRow>

		<MetricRow
			label="Temperature"
			value={reading('cpuTemperatureC', degrees)}
			tone="var(--amber)"
			stats={summarise(series?.cpuTemperatureC, degrees)}
		>
			<!-- Not zero-based like the other two: nothing here runs near an ambient
			     0°C, so the bottom 40° of the axis would be empty and the trace flat
			     against the top of it. -->
			<Trace
				lines={[{ id: 'temperature', points: series?.cpuTemperatureC, tone: 'var(--amber)' }]}
				domain={[40, 100]}
				format={degrees}
				marks={[60, 80]}
			/>
		</MetricRow>
	</div>
{/snippet}

{#snippet memory()}
	<div class="bleed bands memory">
		<div class="band" style="--cells: minmax(0, 1fr) minmax(0, 2fr)">
			<Dial
				label="RAM usage"
				percent={snapshot?.memoryPercent}
				tone="var(--mint)"
				detail={snapshot
					? `${bytes(snapshot.memoryUsedBytes)} / ${bytes(snapshot.memoryTotalBytes)}`
					: '—'}
			/>

			<Panel label="Memory history">
				<!-- Used, cache and free, which is how the memory is actually divided: the
				     cache is the part the machine would give back under pressure. -->
				<Stack bands={ram} note="no memory history yet" />
			</Panel>
		</div>

		<div class="band pressure">
			<Panel label="Pressure">
				<!-- No domain: this reading lives in hundredths of a percent, so the scale
				     is the range it covered rather than the 0-100 a share could take.
				     Some is any task waiting on memory, full is every task waiting at
				     once — the second is the one that means the machine stopped. -->
				<Trace
					lines={[
						{ id: 'some', points: series?.memoryPressureSomePercent, tone: 'var(--amber)', label: 'Some' },
						{ id: 'full', points: series?.memoryPressureFullPercent, tone: 'var(--coral)', label: 'Full', dashed: true }
					]}
					format={pct}
				/>
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet storage()}
	<!-- The volumes take the first third; the horizon takes the rest, because it is
	     the one chart that reads them together. Everything else about the disks runs
	     along the bottom. -->
	<div class="bleed bands">
		<div class="band" style="--cells: minmax(0, 1fr) minmax(0, 2fr)">
			<div class="stack">
				{#each volumes as vol (vol.id)}
					<!-- The series' last percent, or the live snapshot's until the history
					     has one: the reading is the same either way. -->
					<Capacity
						label="{vol.label} capacity"
						percent={vol.percentNow ?? snapshot?.[`${vol.id}Percent`]}
						tone={vol.tone}
						detail={vol.totalNow ? `${bytes(vol.usedNow)} / ${bytes(vol.totalNow)}` : '—'}
					/>
				{/each}
			</div>

			<Horizon {volumes} />
		</div>

		<div class="band io">
			<Panel label="I/O pulse">
				<!-- Each lane is stretched to its own busiest quarter-hour, so the key
				     quotes that lane's own floor and ceiling in bytes a second. -->
				<Heatmap rows={io} normalise="row" format={rate} note="no io history yet" />
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet network()}
	<!-- Two bands across the section rather than a grid of panels: the throughput
	     and what is left of the link on top, the counts and the probe under it. -->
	<div class="bleed bands">
		<div class="band" style="--cells: minmax(0, 3fr) minmax(10rem, 1fr)">
			<Panel label="Throughput">
				<Trace
					lines={[
						{ id: 'rx', points: rx, tone: 'var(--azure)', label: 'RX' },
						{ id: 'tx', points: tx, tone: 'var(--violet)', label: 'TX' }
					]}
					format={rate}
				/>
			</Panel>

			<Dial
				label="Network utilisation"
				percent={snapshot?.networkUtilizationPercent}
				tone="var(--azure)"
				detail={`${rate(Math.max(snapshot?.networkReceiveBytesPerSecond ?? 0, snapshot?.networkTransmitBytesPerSecond ?? 0))} / ${rate(snapshot?.networkLinkSpeedBytes)}`}
			/>
		</div>

		<!-- One band of four rather than three nested beside one: the counts are
		     peers of the probe, not a group set against it, and the extra level of
		     division was costing each count the width its name needs. The probe
		     takes half again, since it carries a chart and they carry a number. -->
		<div class="band quality" style="--cells: repeat(3, minmax(0, 1fr)) minmax(0, 1.6fr)">
			<!-- Both directions to a count, the way the errors beside them already
			     read: a packet lost on the way out is the same fault as one lost on
			     the way in, and which end it happened at is not something this box
			     can act on. -->
			{#each [
				['Drops', snapshot ? snapshot.networkReceiveDropsPerSecond + snapshot.networkTransmitDropsPerSecond : null],
				['Errors', snapshot ? snapshot.networkReceiveErrorsPerSecond + snapshot.networkTransmitErrorsPerSecond : null],
				['TCP retransmits', snapshot?.networkTcpRetransmitsPerSecond]
			] as [label, value] (label)}
				<Panel {label}>
					<!-- Rounded: these are counts a second, and summing two of them is
					     what turns 0.1 and 0.2 into 0.30000000000000004. The unit sits on
					     the figure's own baseline: it is part of the reading, not a line
					     under it. -->
					<p class="rate">
						<strong>{Number.isFinite(value) ? +value.toFixed(2) : '—'}</strong><small>/s</small>
					</p>
				</Panel>
			{/each}

			<Panel label="HTTP probe latency">
				<p class="latency-reading">
					<strong>{reading('latencyMs', ms)}</strong><span>P95 {summarise(series?.latencyMs, ms)[2][1]}</span>
				</p>
				<Trace lines={[{ id: 'latency', points: series?.latencyMs, tone: 'var(--azure)' }]} format={ms} />
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet time()}
	<div class="bleed bands">
		<div class="band" style="--cells: minmax(0, 2.2fr) minmax(13rem, 1fr)">
			<Panel label="Source offsets">
				<!-- The bar is what each source admits it could be wrong by, so a short
				     one is a source worth following. They agree on the offset to a
				     fraction of a millisecond and differ sevenfold on their confidence,
				     which is the whole reading. -->
				<Spread rows={offsets} format={microseconds} note="no time sources reported" />
			</Panel>

			<div class="sync">
				<Panel label="Sync status">
					<strong class="figure" class:down={!clock?.synchronized}>
						{clock?.synchronized ? clockPosition(currentClockOffset) : 'Not synchronised'}
					</strong>
					{#if clock?.stale}
						<p class="eyebrow stale">Reading is stale</p>
					{/if}
				</Panel>

				<dl class="leaders">
					{#each [
						['RMS offset', microspan(clock?.rmsOffsetSeconds)],
						['Root delay', microspan(clock?.rootDelaySeconds)],
						['Root dispersion', microspan(clock?.rootDispersionSeconds)],
						['Frequency', ppm(clock?.frequencyPpm)],
						['Stratum', clock?.stratum ?? '—'],
						['Leap status', clock?.leapStatus ?? '—']
					] as [name, value] (name)}
						<!-- The filler is the dotted rule the rest of the page measures with,
						     run between the name and its reading. -->
						<div><dt class="eyebrow">{name}</dt><i></i><dd>{value}</dd></div>
					{/each}
				</dl>
			</div>
		</div>

		<div class="band history">
			<Panel label="Offset">
				<Trace
					lines={[{ id: 'offset', points: clockHistory, tone: 'var(--azure)', area: false }]}
					domain={[-clockLimit, clockLimit]}
					marks={[0]}
					format={microseconds}
				/>
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet containers()}
	<!-- Decorative: the section is named by its heading, and the art is thousands
	     of digits to a screen reader. -->
	<div class="art ship" aria-hidden="true"><AsciiShip /></div>
	{#if containerFleet.slots.length}
		<div class="container-shell bleed">
			<div class="band nested container-summary" style="--cells: repeat(3, minmax(0, 1fr))">
				<div><strong>{containerFleet.running}</strong><span class="eyebrow">Running</span></div>
				<div class:warning={containerFleet.unhealthy > 0}><strong>{containerFleet.unhealthy}</strong><span class="eyebrow">Unhealthy</span></div>
				<div><strong>{containerFleet.memory}</strong><span class="eyebrow">In use</span></div>
			</div>

			<div class="band nested container-band">
				{#each containerFleet.slots as slot (slot.name)}
					<div class="container-slot">
						<header class="container-head">
							<h3>{slot.name}</h3>
							<span class="eyebrow" class:warning={!slot.healthy}>{slot.status}</span>
						</header>

						<!-- What it is using of what it was given, in that resource's own
						     colour: the reading, the allowance, and the share between them. -->
						{#each slot.resources as resource (resource.id)}
							<div class="container-resource" style:color={resource.tone}>
								<div class="container-reading">
									<span class="eyebrow">{resource.label}</span>
									<strong>{resource.value}</strong>
									<span>{resource.limit}</span>
								</div>
								<i class="resource-bar"><i style:width="{resource.fill}%"></i></i>
							</div>
						{/each}

						<div class="container-uptime"><span class="eyebrow">Uptime</span><strong>{slot.uptime}</strong></div>
					</div>
				{/each}
			</div>
		</div>
	{:else}
		<Placeholder note="no container data" lines={3} />
	{/if}
{/snippet}

<div class="server">
	<aside class="rail" aria-label="Dashboard sections">
		<div class="rail-art" aria-hidden="true">
			<Placeholder note="ascii" lines={6} />
		</div>

		<nav>
			{#each SECTIONS as section, i (section.id)}
				<a
					class="eyebrow"
					href="#{section.id}"
					aria-current={current === section.id ? 'location' : undefined}
				>
					<span class="idx">{String(i).padStart(2, '0')}</span>
					<span>{section.label}</span>
					<span class="dot" aria-hidden="true"></span>
				</a>
			{/each}
		</nav>

		<div class="rail-foot">
			<span class="eyebrow">Last updated</span>
			<!-- The stamp the snapshot came with, not the clock: this says how fresh
			     the numbers above are, which is not the same as what time it is. -->
			<span class="mono">{stamp(snapshot?.generatedAt)}</span>
		</div>
	</aside>

	<div class="body">
		<!-- The page's own heading. The sections carry the titling now, so this is
		     for the outline rather than the eye: without it the document starts at
		     h2 and the sections are under nothing. -->
		<h1>Server</h1>

		<!-- The rail and the page are the one list, so neither can drift from the
		     other: each section is a box with its own heading, and its body is a
		     snippet looked up by its id. -->
		{#each SECTIONS as section (section.id)}
			<section id={section.id} {@attach spy(section.id)}>
				<h2>{section.label}</h2>
				{@render { uptime, cpu, memory, storage, network, time, containers }[section.id]()}
			</section>
		{/each}
	</div>
</div>

<style>
	.server {
		/* The rail is a fixed column and the dashboard takes the rest. Capped and
		   centred like .page, but wider: this is a dashboard, not prose. */
		--rail: 13rem;
		--stick: calc(var(--nav-pad-top) + 0.5rem);

		display: grid;
		grid-template-columns: var(--rail) minmax(0, 1fr);
		gap: clamp(1.5rem, 3vw, 3rem);
		max-width: 82rem;
		margin-inline: auto;
		padding: clamp(1.5rem, 4vh, 2.5rem) var(--gutter) clamp(3rem, 10vh, 6rem);

		/* The line dividing the two columns, drawn down the page rather than down the
		   rail: the rail is sticky and only as tall as its own contents, so its
		   border would stop partway. Measured on the content box, so it starts level
		   with the title and ends with the last section rather than running out into
		   the page's padding. */
		background: linear-gradient(var(--color-border), var(--color-border)) no-repeat;
		background-origin: content-box;
		background-position: var(--rail) 0;
		background-size: 1px 100%;
	}

	/* Sticky, not fixed: it stays with the column it belongs to at any width, and
	   the shell's overflow: clip does not make a scrollport, so this resolves
	   against the viewport as intended. */
	.rail {
		position: sticky;
		top: var(--stick);
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
		align-self: start;
		max-height: calc(100svh - var(--stick) - 1rem);
		padding-right: 1.25rem;
	}

	nav {
		display: flex;
		flex-direction: column;
		/* The list is the only part allowed to scroll if the sections ever outgrow
		   the viewport; the art and the footer stay put. */
		overflow-y: auto;
		scrollbar-width: thin;
	}

	/* The stops on the rail: the same small caps every label on the page is set
	   in, a size up because this list is navigation rather than a caption. */
	nav a {
		display: grid;
		grid-template-columns: auto 1fr auto;
		gap: 0.6rem;
		align-items: center;
		padding: 0.55rem 0;
		font-size: 0.7rem;
		text-decoration: none;
		transition: color 160ms ease;
	}

	nav a:hover,
	nav a:focus-visible {
		color: var(--color-foreground);
	}

	nav a[aria-current] {
		color: var(--mint);
	}

	.idx {
		font-family: var(--font-mono);
		font-size: 0.65rem;
		letter-spacing: 0.08em;
	}

	.dot {
		width: 0.35rem;
		height: 0.35rem;
		border-radius: 50%;
		background: currentcolor;
		opacity: 0.35;
	}

	nav a[aria-current] .dot {
		box-shadow: 0 0 0.7rem currentcolor;
		opacity: 1;
	}

	.rail-foot {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
		margin-top: auto;
	}

	.mono {
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.72rem;
	}

	/* Read out, never drawn: the sections do the titling, and this is only here so
	   the document has something to start its outline at. */
	h1 {
		position: absolute;
		width: 1px;
		height: 1px;
		margin: -1px;
		overflow: hidden;
		clip-path: inset(50%);
		white-space: nowrap;
	}

	/* A piece of generated ascii art. A character grid has one size — how big one
	   cell is — so the art is sized by setting that from the box it sits in, and
	   --cols is how many cells wide the grid measures: its column count times the
	   0.6021em JetBrains Mono advances per character. Every piece on this page
	   therefore spans its box and shrinks with it. */
	.art {
		container-type: inline-size;
	}

	.art :global(pre) {
		font-size: calc(100cqw / var(--cols));
		/* The generator sets line-height 0.72, which at these sizes lands between
		   pixels (9.55 x 0.72 = 6.88). Painting rounds each row's baseline on its
		   own, so a fractional pitch comes out as a 7, 7, 7, 6 rhythm: every fourth
		   row sits a pixel tight against the one above and the collisions read as
		   horizontal bands across the picture. Rounding the pitch to something a row
		   can be painted at makes every row the same height instead.

		   This is a ratio of the font size, not a fixed height, so it tracks the art
		   as it scales with its container. What it costs is the rounding: the rows
		   are up to half a device pixel off the 0.72, which is under 3% of the
		   picture's height wherever a digit in it is legible. */
		line-height: round(0.72em, var(--device-px, 1px));
	}

	/* 166 columns, which at the width of a section box is the ~9.5px the bull's own
	   digits are set at on a laptop screen. This is the cell size, not a count of
	   what is in any one picture: every piece that heads a section is scaled by it,
	   so a digit is one size across the page whether that art turns out to be 164
	   columns or 166. */
	.dish,
	.ship {
		--cols: 99.95;
	}

	/* A grid of stubs follows it; the foot under the dish brings its own air. */
	.ship {
		margin-bottom: 0.75rem;
	}

	.container-shell {
		margin-inline: calc(-1 * var(--pad));
		border-top: var(--rule);
	}

	/* As many containers across as fit, not a fixed four: between a phone and a
	   desktop, four columns is four columns of collisions. Every slot carries the
	   rule above and to the left of it and the grid is bled a pixel each way, so
	   the ones on the outside land on the section's own border — which is the only
	   version of this that does not have to know how many columns there turned out
	   to be. */
	.container-band {
		/* Through --cells, which is how a band is divided: setting the columns
		   directly is a rule of the same weight as the one it is trying to beat. */
		--cells: repeat(auto-fill, minmax(13rem, 1fr));

		margin-top: -1px;
		margin-left: -1px;
	}

	.container-slot {
		display: grid;
		gap: 1rem;
		min-height: 11rem;
		border-top: var(--rule);
		border-left: var(--rule);
	}

	.container-summary > div {
		display: flex;
		align-items: baseline;
		gap: 0.8rem;
		color: var(--mint);
	}

	.container-summary .eyebrow {
		color: var(--text-dim);
	}

	.container-head,
	.container-reading,
	.container-uptime {
		display: flex;
		align-items: baseline;
		justify-content: space-between;
		gap: 0.75rem;
	}

	.container-head h3 {
		margin: 0;
		font-size: 0.68rem;
		letter-spacing: 0.14em;
		text-transform: uppercase;
	}

	.container-head span {
		color: var(--mint);
	}

	.container-resource {
		display: grid;
		gap: 0.45rem;
	}

	.container-reading strong,
	.container-reading > span:last-child,
	.container-uptime strong {
		font-family: var(--font-mono);
		font-size: 0.68rem;
		font-weight: 400;
	}

	.container-reading strong {
		margin-left: auto;
	}

	.container-reading > span:last-child {
		min-width: 4.2rem;
		color: var(--text-dim);
		text-align: right;
		text-transform: uppercase;
	}

	.resource-bar {
		display: block;
		height: 2px;
		background: var(--color-border);
	}

	.resource-bar i {
		display: block;
		height: 100%;
		min-width: 0;
		background: currentcolor;
	}

	.container-uptime {
		margin-top: auto;
		padding-top: 0.75rem;
		border-top: var(--rule);
	}

	/* Both as specific as the rule each is turning off, or the cell keeps the mint
	   it wears when everything is well and a count of unhealthy containers reads
	   as a good number. */
	.container-summary > .warning,
	.container-head span.warning {
		color: var(--coral);
	}


	/* A section is one box, divided rather than filled with smaller ones: the parts
	   inside wear no frame of their own and are separated by a rule instead, drawn a
	   shade under the box's own border so the box stays the strongest line on the
	   page.

	   Every rule runs the full width or height of what it divides — wall to wall, not
	   inset by the padding — which it does by bleeding out by --pad and putting the
	   same back as padding. --divide is the air either side of a rule, and the gap of
	   whatever lays the parts out, so the two cannot drift apart. */
	section {
		--pad: clamp(1rem, 2.5vw, 1.75rem);
		--rule: 1px solid color-mix(in srgb, var(--color-border) 75%, transparent);
		--divide: clamp(1rem, 2vw, 1.5rem);

		/* No panel in here is a heading of its own — the section's own h2 is that —
		   so every one of their titles is turned down to a label. */
		--title-size: 0.68rem;
		--title-color: var(--text-faint);

		display: grid;
		gap: var(--divide);
		margin-bottom: clamp(2rem, 6vh, 3.5rem);
		padding: var(--pad);
		border: 1px solid var(--color-border);
		border-radius: 0.35rem;
		/* Clears the sticky rail when a link jumps here. */
		scroll-margin-top: var(--stick);
	}

	/* Nothing follows the last one, and the gap it would leave is what the column's
	   divider would have to run past. */
	section:last-child {
		margin-bottom: 0;
	}

	/* The heading is separated from the section's contents by the same rule that
	   divides them from each other. */
	h2 {
		margin: 0 calc(-1 * var(--pad));
		padding: 0 var(--pad) var(--divide);
		border-bottom: var(--rule);
		font-size: 1.05rem;
		font-weight: 700;
		letter-spacing: 0.16em;
		text-transform: uppercase;
	}

	/* Readings one under the other with a line between them, run out to the edges
	   of whatever holds them — the section itself for a column of metric rows, a
	   band's cell for the volumes, which is the same distance either way. */
	.stack {
		display: grid;
		gap: var(--divide);
		align-content: start;
	}

	.stack > :global(*) + :global(*) {
		margin-inline: calc(-1 * var(--pad));
		padding-top: var(--divide);
		padding-inline: var(--pad);
		border-top: var(--rule);
	}

	/* Taller than a row's sparkline: this chart is three bands deep and the dial
	   beside it is a shape of its own, not a line of text. */
	.memory {
		--graph-min: 9rem;
	}

	/* A chart read across rather than down: the height only has to be enough to see
	   a line move. */
	.pressure {
		--graph-min: 6rem;
	}

	/* A band across a section: cells side by side, a rule between them and one over
	   the lot. `--cells` is how they divide; the default is equal shares. Nest one
	   in a cell of another to divide it again — the inner band is the division, not
	   a second row, so it drops the rule and the padding it would otherwise wear. */
	.band {
		display: grid;
		grid-template-columns: var(--cells, repeat(auto-fit, minmax(0, 1fr)));
		border-top: var(--rule);
	}

	/* :global, because a cell is often a component's own root — Panel's — and a
	   scoped selector cannot reach one. */
	.band > :global(*) {
		padding: var(--divide) var(--pad);
	}

	.band > :global(* + *) {
		border-left: var(--rule);
	}

	.band.nested {
		padding: 0;
		border-top: 0;
	}

	/* Out to the section's own edges, which is where a band's rules have to end,
	   and down to the bottom one, which the section's padding would otherwise hold
	   it off. */
	.bleed {
		margin-inline: calc(-1 * var(--pad));
		margin-bottom: calc(-1 * var(--pad));
	}

	/* Every reading that sits in a band, at one size: these are rows of figures
	   read across and compared down the page, so a cell does not get to pick a
	   size of its own. Mono, unlike the .figure a whole section is known by —
	   these are counts, not headlines. The colour is the band's, since a reading
	   that is off takes its own. */
	.headline strong,
	.rate strong,
	.latency-reading strong,
	.container-summary strong {
		font-family: var(--font-mono);
		font-size: 1.45rem;
	}

	.headline strong,
	.rate strong {
		color: var(--mint);
	}

	.headline strong {
		text-transform: uppercase;
	}

	.headline .down {
		color: var(--coral);
	}

	.headline .unknown {
		color: var(--text-faint);
	}

	/* Wall to wall along the foot of the section: a trace this wide is read across,
	   and the height only has to be enough to see the line move. */
	.history {
		--graph-min: 10rem;
	}

	.sync {
		display: grid;
		gap: var(--divide);
		align-content: start;
	}

	.sync .figure {
		display: flex;
		align-items: center;
		gap: 0.6rem;
		color: var(--mint);
		text-transform: uppercase;
	}

	.sync .down {
		color: var(--coral);
	}

	.stale {
		margin: 0.35rem 0 0;
		color: var(--coral);
	}

	/* Name, reading, and the dots that carry the eye between them. */
	.leaders {
		display: grid;
		gap: 0.6rem;
		margin: 0;
	}

	.leaders div {
		display: grid;
		grid-template-columns: auto minmax(1rem, 1fr) auto;
		gap: 0.5rem;
		align-items: baseline;
	}

	.leaders i {
		height: 1px;
		color: var(--color-border);
		background-image: var(--dot-row);
		transform: translateY(-0.15em);
	}

	.leaders dd {
		margin: 0;
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.7rem;
	}


	/* The io map wants a wider gutter than the graphs above it: these row labels are
	   words, not core numbers. Taller too — four lanes divide the block, so the floor
	   has to leave each one a cell worth looking at. */
	.io {
		--axis-w: 5rem;
		--graph-min: 8rem;
	}

	/* A section that is nothing but bands, stacked. It starts against the rule under
	   the heading rather than a gap below it, so the first band brings no rule of
	   its own. Tall enough that eight lanes can divide it and each still be a lane,
	   which is the deepest thing any band holds. */
	.bands {
		--graph-min: 13rem;

		margin-top: calc(-1 * var(--divide));
	}

	.bands > .band:first-child {
		border-top: 0;
	}

	.quality {
		--graph-min: 6rem;
	}

	/* The unit belongs to the number, so it sits on its baseline rather than under
	   it. */
	.rate,
	.latency-reading {
		display: flex;
		align-items: baseline;
		gap: 0.3rem;
		margin: 0;
	}

	.latency-reading {
		gap: 1.25rem;
	}

	.rate small,
	.latency-reading span {
		color: var(--text-faint);
		font-family: var(--font-mono);
		font-size: 0.6rem;
	}

	.latency-reading strong {
		color: var(--violet);
	}

	.latency-reading strong {
		color: var(--violet);
	}

	/* Under this the rail cannot hold its column and its labels at once. It goes
	   horizontal along the top instead, still sticky, still the way through the
	   page. */
	@media (max-width: 52rem) {
		.server {
			grid-template-columns: minmax(0, 1fr);
			gap: 1rem;
			/* One column, nothing to divide. */
			background: none;
		}

		.rail {
			z-index: 2;
			flex-direction: row;
			align-items: center;
			gap: 1rem;
			max-height: none;
			padding: 0.5rem 0;
			border-bottom: 1px solid var(--color-border);
			background: var(--color-background);
		}

		.rail-art,
		.rail-foot {
			display: none;
		}

		nav {
			flex-direction: row;
			gap: 1.25rem;
			overflow-x: auto;
		}

		nav a {
			padding: 0.25rem 0;
			white-space: nowrap;
		}

		.stack {
			--graph-min: 5rem;
		}

		/* No band holds its cells side by side at this width: they stack, and the
		   rule between them lies down with them. The containers are the exception —
		   that grid already fits itself to whatever width it is given. */
		.band:not(.container-band) {
			grid-template-columns: minmax(0, 1fr);
		}

		.band:not(.container-band) > :global(* + *) {
			border-top: var(--rule);
			border-left: 0;
		}

	}
</style>
