<script>
	// Generated by ../asciiArt from the source photographs there.
	import AsciiDish from '$lib/components/AsciiDish.svelte';
	import AsciiShip from '$lib/components/AsciiShip.svelte';
	import Capacity from '$lib/components/Capacity.svelte';
	import Dial from '$lib/components/Dial.svelte';
	import Heatmap from '$lib/components/Heatmap.svelte';
	import Horizon from '$lib/components/Horizon.svelte';
	import MetricRow from '$lib/components/MetricRow.svelte';
	import Panel from '$lib/components/Panel.svelte';
	import Placeholder from '$lib/components/Placeholder.svelte';
	import Spread from '$lib/components/Spread.svelte';
	import Stack from '$lib/components/Stack.svelte';
	import Trace from '$lib/components/Trace.svelte';
	import {
		bytes,
		clockPosition,
		degrees,
		duration,
		microseconds,
		microspan,
		pct,
		ppm,
		rate,
		seconds,
		span,
		stamp
	} from '$lib/format.js';
	import { memoryBands } from '$lib/memory.js';
	import { RANGE, server, watch } from '$lib/server.svelte.js';
	import { bucket, last, mean, outages, summarise } from '$lib/stats.js';
	import { volume } from '$lib/storage.js';
	import { spread } from '$lib/time.js';

	/* Wireframe. CPU and storage are wired up; everything else is a placeholder
	   holding the shape of what goes there. One entry per section of the page and
	   per stop on the rail: a section is a box on the page, its own heading, and
	   its own place in the list. */
	const SECTIONS = [
		{ id: 'uptime', label: 'Uptime' },
		{ id: 'cpu', label: 'CPU' },
		{ id: 'memory', label: 'Memory' },
		{ id: 'storage', label: 'Storage' },
		{ id: 'network', label: 'Network' },
		{ id: 'time', label: 'Time' },
		{ id: 'containers', label: 'Containers' }
	];

	/* The two drives. One entry each: the id is the prefix every one of their
	   series is named with, and the tone is theirs wherever they appear — capacity
	   box, horizon, io lane. */
	const DISKS = [
		{ id: 'nvme', label: 'NVMe', tone: 'var(--violet)' },
		{ id: 'ssd', label: 'SSD', tone: 'var(--azure)' }
	];

	/* Columns in the heatmap. The series is 24h at five-minute steps, so this is
	   about a quarter-hour a cell — fine enough to see a spike, coarse enough that
	   a cell is still a cell rather than a hairline. */
	const HEAT_COLUMNS = 72;

	$effect(watch);

	let snapshot = $derived(server.snapshot);
	let series = $derived(server.series);
	let month = $derived(server.month);

	/* How the machine's memory is divided, as three shares of the whole. */
	let ram = $derived(memoryBands(series));

	/* Each volume worked out from its own 30-day series: where it is, which way it
	   is going, and when that runs out. The capacity boxes and the horizon are the
	   same objects seen two ways. */
	let volumes = $derived(
		DISKS.map((disk) =>
			volume({
				...disk,
				used: month?.[`${disk.id}UsedBytes`],
				available: month?.[`${disk.id}AvailableBytes`],
				percent: month?.[`${disk.id}Percent`]
			})
		)
	);

	/* The live reading, written the way $lib/format.js writes that quantity — the
	   same spelling the stats and the map key beside it use, so one number is not
	   quoted to two precisions in one box. */
	const reading = (key, format) => format(snapshot?.[key]);

	let current = $state(SECTIONS[0].id);

	/* Which section the rail marks. An observer on the section itself, rather than
	   scroll maths or a document lookup: it is the platform's own answer to "what
	   is on screen". Top-biased margin so the mark flips when a heading reaches
	   the upper third, which is where the eye is, not when the section is half
	   gone. */
	const spy = (id) => (element) => {
		const observer = new IntersectionObserver(
			([entry]) => {
				if (entry.isIntersecting) current = id;
			},
			{ rootMargin: '-20% 0px -70% 0px' }
		);

		observer.observe(element);
		return () => observer.disconnect();
	};

	/* Read and write on each disk, a lane of the pulse map each. The two sit orders
	   of magnitude apart on the same drive, so the map normalises per row — a lane
	   says when that stream was busy, not how it compares to the one under it. The
	   current rate is on the right of each lane for that. */
	let io = $derived(
		DISKS.flatMap(({ id, label, tone }) =>
			['Read', 'Write'].map((direction) => {
				const points = series?.[`${id}${direction}BytesPerSecond`];
				return {
					id: `${label} ${direction.toLowerCase()}`,
					group: label,
					tone,
					now: rate(last(points)),
					cells: bucket(points, HEAT_COLUMNS)
				};
			})
		).filter((lane) => lane.cells.length)
	);

	/* The 24h scale both maps of the window are labelled with. */
	const DAY_TICKS = ['24h ago', '18h', '12h', '6h', 'Now'];

	/* Per-core utilisation as a map: one row a core, one cell a bucket, straight
	   off the same 0-100% scale the traces are drawn against. */
	let cores = $derived(
		Object.entries(series?.cpuPerCorePercent ?? {})
			.sort(([a], [b]) => Number(a) - Number(b))
			.map(([id, points]) => ({
				id: `C${id}`,
				now: pct(last(points)),
				cells: bucket(points, HEAT_COLUMNS)
			}))
	);

	let rx = $derived(series?.networkReceiveBytesPerSecond ?? []);
	let tx = $derived(series?.networkTransmitBytesPerSecond ?? []);
	const ms = (v) => (Number.isFinite(v) ? `${Math.round(v)} ms` : '—');

	/* Availability is read in nines, so it keeps two decimals where pct() would
	   round 99.98% up to a month without an outage in it. */
	const nines = (v) => (Number.isFinite(v) ? `${v.toFixed(2)}%` : '—');

	/* The status series is 1 for a poll the machine answered and 0 for one it did
	   not, so its mean is the share of the window the machine was up.

	   Read off the 24h series and not the 30d one, even though a month is the
	   window worth quoting: the API downsamples the long range to two-hour steps
	   and does not carry the failures through, so every one of its readings is
	   exactly 1 and an outage that plainly happened is not in it. A number that
	   cannot go below 100% is not an availability figure. */
	let statusDay = $derived(series?.status ?? []);
	let availability = $derived(statusDay.length ? mean(statusDay.map((p) => p[1])) * 100 : null);
	let incidents = $derived(outages(statusDay));

	let online = $derived(snapshot?.server === 'online');

	/* The clock, and every source it listens to as a reading with a bound. */
	let clock = $derived(snapshot?.time);
	let offsets = $derived(spread(clock));

	/* Chrony reports the correction needed to reach NTP: a negative correction
	   means this machine is fast. Flip it here so positive reads naturally as
	   PHOBOS ahead and negative as PHOBOS behind. */
	let clockHistory = $derived(
		(series?.timeSystemOffsetSeconds ?? []).map(([time, offset]) => [time, -offset])
	);
	let currentClockOffset = $derived(
		Number.isFinite(clock?.systemOffsetSeconds) ? -clock.systemOffsetSeconds : null
	);
	let clockLimit = $derived.by(() => {
		const greatest = Math.max(50e-6, ...clockHistory.map((point) => Math.abs(point[1])));
		return Math.ceil((greatest * 1.15) / 50e-6) * 50e-6;
	});
</script>

<svelte:head>
	<title>Server — Joshua Smith</title>
</svelte:head>

{#snippet stub(label, note, lines)}
	<Panel {label}>
		<Placeholder {note} {lines} />
	</Panel>
{/snippet}

{#snippet uptime()}
	<!-- Decorative: the section is named by its heading, and the art is thousands
	     of digits to a screen reader. -->
	<div class="art dish" aria-hidden="true"><AsciiDish /></div>

	<div class="band bleed centred">
		<div>
			<span class="eyebrow">Uptime</span>
			<!-- The state is the dot and the word both, not the colour: "up" and "down"
			     are the reading, and the dot only agrees with them. -->
			<strong class:down={!online}>
				<i></i>{online ? `Up ${duration(snapshot.uptimeSeconds)}` : 'Down'}
			</strong>
		</div>

		<div>
			<span class="eyebrow">{RANGE} availability</span>
			<strong>{nines(availability)}</strong>
		</div>

		<div>
			<span class="eyebrow">Incidents</span>
			<strong class:down={incidents > 0}>{statusDay.length ? incidents : '—'}</strong>
		</div>

		<div>
			<span class="eyebrow">Next planned outage</span>
			<!-- Nothing scheduled is not a reading in the same sense as the three
			     beside it, and is set back so it does not read as one. -->
			<strong class="unknown">—</strong>
		</div>
	</div>
{/snippet}

{#snippet cpu()}
	<div class="stack">
		<MetricRow
			label="Usage"
			value={reading('cpuPercent', pct)}
			tone="var(--mint)"
			stats={summarise(series?.cpuPercent, pct)}
		>
			<!-- The key spells out the band the colours cover, since the map is
			     stretched to the range the cores actually ran at. -->
			<Heatmap rows={cores} format={pct} note="no per-core history yet" />
		</MetricRow>

		<MetricRow
			label="Pressure"
			value={reading('cpuPressurePercent', pct)}
			tone="var(--coral)"
			stats={summarise(series?.cpuPressurePercent, pct)}
		>
			<!-- Sustained pressure is the reading that matters rather than any one
			     spike, so the rules are the two levels worth seeing a trace cross. -->
			<Trace
				lines={[{ id: 'pressure', points: series?.cpuPressurePercent, tone: 'var(--coral)' }]}
				domain={[0, 100]}
				format={pct}
				marks={[25, 50]}
			/>
		</MetricRow>

		<MetricRow
			label="Temperature"
			value={reading('cpuTemperatureC', degrees)}
			tone="var(--amber)"
			stats={summarise(series?.cpuTemperatureC, degrees)}
		>
			<!-- Not zero-based like the other two: nothing here runs near an ambient
			     0°C, so the bottom 40° of the axis would be empty and the trace flat
			     against the top of it. -->
			<Trace
				lines={[{ id: 'temperature', points: series?.cpuTemperatureC, tone: 'var(--amber)' }]}
				domain={[40, 100]}
				format={degrees}
				marks={[60, 80]}
			/>
		</MetricRow>
	</div>
{/snippet}

{#snippet memory()}
	<div class="split memory">
		<Dial
			label="RAM usage"
			percent={snapshot?.memoryPercent}
			tone="var(--mint)"
			detail={snapshot
				? `${bytes(snapshot.memoryUsedBytes)} / ${bytes(snapshot.memoryTotalBytes)}`
				: '—'}
		/>

		<div class="beside">
			<Panel label="Memory history">
				<!-- Used, cache and free, which is how the memory is actually divided: the
				     cache is the part the machine would give back under pressure. -->
				<Stack bands={ram} ticks={DAY_TICKS} note="no memory history yet" />
			</Panel>
		</div>

		<div class="wide">
			<Panel label="Pressure">
				<!-- No domain: this reading lives in hundredths of a percent, so the scale
				     is the range it covered rather than the 0-100 a share could take.
				     Some is any task waiting on memory, full is every task waiting at
				     once — the second is the one that means the machine stopped. -->
				<Trace
					lines={[
						{ id: 'some', points: series?.memoryPressureSomePercent, tone: 'var(--amber)', label: 'Some' },
						{ id: 'full', points: series?.memoryPressureFullPercent, tone: 'var(--coral)', label: 'Full', dashed: true }
					]}
					format={pct}
				/>
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet storage()}
	<!-- Three lanes. The volumes take the first third; the horizon takes the rest,
	     because it is the one chart that reads them together. Everything else about
	     the disks runs along the bottom. -->
	<div class="split">
		<div class="volumes">
			{#each volumes as vol (vol.id)}
				<!-- The series' last percent, or the live snapshot's until the history
				     has one: the reading is the same either way. -->
				<Capacity
					label="{vol.label} capacity"
					percent={vol.percentNow ?? snapshot?.[`${vol.id}Percent`]}
					tone={vol.tone}
					detail={vol.totalNow ? `${bytes(vol.usedNow)} / ${bytes(vol.totalNow)}` : '—'}
				/>
			{/each}
		</div>

		<div class="beside">
			<Horizon {volumes} />
		</div>

		<div class="wide io">
			<Panel label="I/O pulse">
				<!-- Each lane is stretched to its own busiest quarter-hour, so the key
				     quotes that lane's own floor and ceiling in bytes a second. -->
				<Heatmap
					rows={io}
					ticks={DAY_TICKS}
					normalise="row"
					format={rate}
					note="no io history yet"
				/>
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet network()}
	<!-- Two bands across the section rather than a grid of panels: the throughput
	     and what is left of the link on top, the counts and the probe under it. -->
	<div class="bleed bands">
		<div class="band" style="--cells: minmax(0, 3fr) minmax(10rem, 1fr)">
			<div>
				<Panel label="Throughput">
					<Trace
						lines={[
							{ id: 'rx', points: rx, tone: 'var(--azure)', label: 'RX' },
							{ id: 'tx', points: tx, tone: 'var(--mint)', label: 'TX' }
						]}
						format={rate}
					/>
				</Panel>
			</div>
			<div>
				<Dial
					label="Network utilisation"
					percent={snapshot?.networkUtilizationPercent}
					tone="var(--azure)"
					detail={`${rate(Math.max(snapshot?.networkReceiveBytesPerSecond ?? 0, snapshot?.networkTransmitBytesPerSecond ?? 0))} / ${rate(snapshot?.networkLinkSpeedBytes)}`}
				/>
			</div>
		</div>

		<!-- The counts take the larger share: their names have to fit across it, and
		     the longest of them ("TCP retransmits") is what sets the split. -->
		<div class="band quality" style="--cells: minmax(0, 1.2fr) minmax(0, 1fr)">
			<div class="band nested" style="--cells: repeat(3, minmax(0, 1fr))">
				<!-- Both directions to a count, the way the errors beside them already
				     read: a packet lost on the way out is the same fault as one lost on
				     the way in, and which end it happened at is not something this box
				     can act on. -->
				{#each [
					['Drops', snapshot ? snapshot.networkReceiveDropsPerSecond + snapshot.networkTransmitDropsPerSecond : null],
					['Errors', snapshot ? snapshot.networkReceiveErrorsPerSecond + snapshot.networkTransmitErrorsPerSecond : null],
					['TCP retransmits', snapshot?.networkTcpRetransmitsPerSecond]
				] as [label, value]}
					<!-- Rounded: these are counts a second, and summing two of them is
					     what turns 0.1 and 0.2 into 0.30000000000000004. -->
					<div><span class="eyebrow">{label}</span><strong>{Number.isFinite(value) ? +value.toFixed(2) : '—'}</strong><small>/s</small></div>
				{/each}
			</div>

			<div>
				<Panel label="HTTP probe latency">
					<div class="latency-reading"><strong>{reading('latencyMs', ms)}</strong><span>P95 {summarise(series?.latencyMs, ms)[2][1]}</span></div>
					<Trace lines={[{ id: 'latency', points: series?.latencyMs, tone: 'var(--violet)' }]} format={ms} />
				</Panel>
			</div>
		</div>
	</div>
{/snippet}

{#snippet time()}
	<div class="bleed bands">
		<div class="band" style="--cells: minmax(0, 2.2fr) minmax(13rem, 1fr)">
			<div class="offsets">
				<Panel label="Source offsets">
					<!-- The bar is what each source admits it could be wrong by, so a short
					     one is a source worth following. They agree on the offset to a
					     fraction of a millisecond and differ sevenfold on their confidence,
					     which is the whole reading. -->
					<Spread rows={offsets} format={seconds} note="no time sources reported" />
				</Panel>
			</div>

			<div class="sync">
				<Panel label="Sync status">
					<strong class="figure" class:down={!clock?.synchronized}>
						{clock?.synchronized ? clockPosition(currentClockOffset) : 'Not synchronised'}
					</strong>
					{#if clock?.stale}
						<p class="eyebrow stale">Reading is stale</p>
					{/if}
				</Panel>

				<dl class="leaders">
					{#each [
						['RMS offset', microspan(clock?.rmsOffsetSeconds)],
						['Root delay', span(clock?.rootDelaySeconds)],
						['Root dispersion', span(clock?.rootDispersionSeconds)],
						['Frequency', ppm(clock?.frequencyPpm)],
						['Stratum', clock?.stratum ?? '—'],
						['Leap status', clock?.leapStatus ?? '—']
					] as [name, value] (name)}
						<!-- The filler is the dotted rule the rest of the page measures with,
						     run between the name and its reading. -->
						<div><dt class="eyebrow">{name}</dt><i></i><dd>{value}</dd></div>
					{/each}
				</dl>
			</div>
		</div>

		<div class="band history">
			<div>
				<Panel label="Offset">
					<div class="offset-chart">
					<Trace
						lines={[
							{ id: 'offset', points: clockHistory, tone: 'var(--mint)', area: false }
						]}
						domain={[-clockLimit, clockLimit]}
						marks={[0]}
						format={microseconds}
					/>
					</div>
				</Panel>
			</div>
		</div>
	</div>
{/snippet}

{#snippet containers()}
	<!-- Decorative: the section is named by its heading, and the art is thousands
	     of digits to a screen reader. -->
	<div class="art ship" aria-hidden="true"><AsciiShip /></div>
	<div class="grid">
		{#each Array.from({ length: 4 })}
			{@render stub('Container', 'cpu · mem · status', 3)}
		{/each}
	</div>
	<div class="grid" style="--min: 14rem">
		{#each Array.from({ length: 3 })}
			{@render stub('Container', 'cpu · mem · status', 3)}
		{/each}
	</div>
{/snippet}

<div class="server">
	<aside class="rail" aria-label="Dashboard sections">
		<div class="rail-art" aria-hidden="true">
			<Placeholder note="ascii" lines={6} />
		</div>

		<nav>
			{#each SECTIONS as section, i (section.id)}
				<a
					class="eyebrow"
					href="#{section.id}"
					aria-current={current === section.id ? 'location' : undefined}
				>
					<span class="idx">{String(i).padStart(2, '0')}</span>
					<span>{section.label}</span>
					<span class="dot" aria-hidden="true"></span>
				</a>
			{/each}
		</nav>

		<div class="rail-foot">
			<span class="eyebrow">Last updated</span>
			<!-- The stamp the snapshot came with, not the clock: this says how fresh
			     the numbers above are, which is not the same as what time it is. -->
			<span class="mono">{stamp(snapshot?.generatedAt)}</span>
		</div>
	</aside>

	<div class="body">
		<!-- The page's own heading. The sections carry the titling now, so this is
		     for the outline rather than the eye: without it the document starts at
		     h2 and the sections are under nothing. -->
		<h1>Server</h1>

		<!-- The rail and the page are the one list, so neither can drift from the
		     other: each section is a box with its own heading, and its body is a
		     snippet looked up by its id. -->
		{#each SECTIONS as section (section.id)}
			<section id={section.id} {@attach spy(section.id)}>
				<h2>{section.label}</h2>
				{@render { uptime, cpu, memory, storage, network, time, containers }[section.id]()}
			</section>
		{/each}
	</div>
</div>

<style>
	.server {
		/* The rail is a fixed column and the dashboard takes the rest. Capped and
		   centred like .page, but wider: this is a dashboard, not prose. */
		--rail: 13rem;
		--stick: calc(var(--nav-pad-top) + 0.5rem);

		display: grid;
		grid-template-columns: var(--rail) minmax(0, 1fr);
		gap: clamp(1.5rem, 3vw, 3rem);
		max-width: 82rem;
		margin-inline: auto;
		padding: clamp(1.5rem, 4vh, 2.5rem) var(--gutter) clamp(3rem, 10vh, 6rem);

		/* The line dividing the two columns, drawn down the page rather than down the
		   rail: the rail is sticky and only as tall as its own contents, so its
		   border would stop partway. Measured on the content box, so it starts level
		   with the title and ends with the last section rather than running out into
		   the page's padding. */
		background: linear-gradient(var(--color-border), var(--color-border)) no-repeat;
		background-origin: content-box;
		background-position: var(--rail) 0;
		background-size: 1px 100%;
	}

	/* Sticky, not fixed: it stays with the column it belongs to at any width, and
	   the shell's overflow: clip does not make a scrollport, so this resolves
	   against the viewport as intended. */
	.rail {
		position: sticky;
		top: var(--stick);
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
		align-self: start;
		max-height: calc(100svh - var(--stick) - 1rem);
		padding-right: 1.25rem;
	}

	nav {
		display: flex;
		flex-direction: column;
		/* The list is the only part allowed to scroll if the sections ever outgrow
		   the viewport; the art and the footer stay put. */
		overflow-y: auto;
		scrollbar-width: thin;
	}

	/* The stops on the rail: the same small caps every label on the page is set
	   in, a size up because this list is navigation rather than a caption. */
	nav a {
		display: grid;
		grid-template-columns: auto 1fr auto;
		gap: 0.6rem;
		align-items: center;
		padding: 0.55rem 0;
		font-size: 0.7rem;
		text-decoration: none;
		transition: color 160ms ease;
	}

	nav a:hover,
	nav a:focus-visible {
		color: var(--color-foreground);
	}

	nav a[aria-current] {
		color: var(--mint);
	}

	.idx {
		font-family: var(--font-mono);
		font-size: 0.65rem;
		letter-spacing: 0.08em;
	}

	.dot {
		width: 0.35rem;
		height: 0.35rem;
		border-radius: 50%;
		background: currentcolor;
		opacity: 0.35;
	}

	nav a[aria-current] .dot {
		box-shadow: 0 0 0.7rem currentcolor;
		opacity: 1;
	}

	.rail-foot {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
		margin-top: auto;
	}

	.mono {
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.72rem;
	}

	/* Read out, never drawn: the sections do the titling, and this is only here so
	   the document has something to start its outline at. */
	h1 {
		position: absolute;
		width: 1px;
		height: 1px;
		margin: -1px;
		overflow: hidden;
		clip-path: inset(50%);
		white-space: nowrap;
	}

	/* A piece of generated ascii art. A character grid has one size — how big one
	   cell is — so the art is sized by setting that from the box it sits in, and
	   --cols is how many cells wide the grid measures: its column count times the
	   0.6021em JetBrains Mono advances per character. Every piece on this page
	   therefore spans its box and shrinks with it. */
	.art {
		container-type: inline-size;
	}

	.art :global(pre) {
		font-size: calc(100cqw / var(--cols));
		/* The generator sets line-height 0.72, which at these sizes lands between
		   pixels (9.55 x 0.72 = 6.88). Painting rounds each row's baseline on its
		   own, so a fractional pitch comes out as a 7, 7, 7, 6 rhythm: every fourth
		   row sits a pixel tight against the one above and the collisions read as
		   horizontal bands across the picture. Rounding the pitch to something a row
		   can be painted at makes every row the same height instead.

		   This is a ratio of the font size, not a fixed height, so it tracks the art
		   as it scales with its container. What it costs is the rounding: the rows
		   are up to half a device pixel off the 0.72, which is under 3% of the
		   picture's height wherever a digit in it is legible. */
		line-height: round(0.72em, var(--device-px, 1px));
	}

	/* 166 columns, which at the width of a section box is the ~9.5px the bull's own
	   digits are set at on a laptop screen. This is the cell size, not a count of
	   what is in any one picture: every piece that heads a section is scaled by it,
	   so a digit is one size across the page whether that art turns out to be 164
	   columns or 166. */
	.dish,
	.ship {
		--cols: 99.95;
	}

	/* A grid of stubs follows it; the foot under the dish brings its own air. */
	.ship {
		margin-bottom: 0.75rem;
	}


	/* A section is one box, divided rather than filled with smaller ones: the parts
	   inside wear no frame of their own and are separated by a rule instead, drawn a
	   shade under the box's own border so the box stays the strongest line on the
	   page.

	   Every rule runs the full width or height of what it divides — wall to wall, not
	   inset by the padding — which it does by bleeding out by --pad and putting the
	   same back as padding. --divide is the air either side of a rule, and the gap of
	   whatever lays the parts out, so the two cannot drift apart. */
	section {
		--pad: clamp(1rem, 2.5vw, 1.75rem);
		--rule: 1px solid color-mix(in srgb, var(--color-border) 75%, transparent);
		--divide: clamp(1rem, 2vw, 1.5rem);

		/* No panel in here is a heading of its own — the section's own h2 is that —
		   so every one of their titles is turned down to a label. */
		--title-size: 0.68rem;
		--title-color: var(--text-faint);

		display: grid;
		gap: var(--divide);
		margin-bottom: clamp(2rem, 6vh, 3.5rem);
		padding: var(--pad);
		border: 1px solid var(--color-border);
		border-radius: 0.35rem;
		/* Clears the sticky rail when a link jumps here. */
		scroll-margin-top: var(--stick);
	}

	/* Nothing follows the last one, and the gap it would leave is what the column's
	   divider would have to run past. */
	section:last-child {
		margin-bottom: 0;
	}

	/* The heading is separated from the section's contents by the same rule that
	   divides them from each other. */
	h2 {
		margin: 0 calc(-1 * var(--pad));
		padding: 0 var(--pad) var(--divide);
		border-bottom: var(--rule);
		font-size: 1.05rem;
		font-weight: 700;
		letter-spacing: 0.16em;
		text-transform: uppercase;
	}

	/* Rows of cards that collapse on their own terms rather than at a shared
	   breakpoint: auto-fit gives the columns way when the cells would be too narrow
	   to read, at whatever width that happens to be. `--min` is how narrow that is
	   for the cards in question. */
	.grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(var(--min, 11rem), 1fr));
		gap: var(--divide);
	}

	/* A third for one reading, the rest for the chart beside it. Storage puts the
	   volumes in one column and a horizon in the other, memory a dial and a
	   history. */
	.split {
		display: grid;
		grid-template-columns: minmax(0, 1fr) minmax(0, 2fr);
		gap: var(--divide);
	}

	/* Whatever sits in the second column carries the line down the middle, top to
	   bottom: up to the rule under the heading, down to the one over the chart
	   beneath — the negative margins are the gaps either end. */
	.beside {
		display: grid;
		margin-top: calc(-1 * var(--divide));
		margin-bottom: calc(-1 * var(--divide));
		padding-top: var(--divide);
		padding-left: var(--divide);
		border-left: var(--rule);
	}

	/* The volumes, one under the other, a line between them. */
	.volumes {
		--bleed-end: var(--divide);

		display: grid;
		gap: var(--divide);
		align-content: start;
	}

	.stack {
		display: grid;
		gap: var(--divide);
	}

	/* A rule between two stacked readings, run out to the section's own edges. The
	   volumes are the exception at their right edge: they stop at the line down the
	   middle, which is what makes the two meet in a T rather than crossing. */
	.stack > :global(*) + :global(*),
	.volumes > :global(*) + :global(*) {
		margin-left: calc(-1 * var(--pad));
		margin-right: calc(-1 * var(--bleed-end, var(--pad)));
		padding-top: var(--divide);
		padding-left: var(--pad);
		padding-right: var(--bleed-end, var(--pad));
		border-top: var(--rule);
	}

	/* Taller than a row's sparkline: this chart is three bands deep and the dial
	   beside it is a shape of its own, not a line of text. */
	.memory {
		--graph-min: 9rem;
	}

	/* A chart that runs the width of the row rather than sitting in one of its
	   columns. Shorter than the boxes above it: a chart this wide reads across, and
	   the height only has to be enough to see a line move. */
	.wide {
		--graph-min: 6rem;

		display: grid;
		grid-column: 1 / -1;
		gap: var(--divide);
		margin-inline: calc(-1 * var(--pad));
		padding-top: var(--divide);
		padding-inline: var(--pad);
		border-top: var(--rule);
	}

	/* A band across a section: cells side by side, a rule between them and one over
	   the lot. `--cells` is how they divide; the default is equal shares. Nest one
	   in a cell of another to divide it again — the inner band is the division, not
	   a second row, so it drops the rule and the padding it would otherwise wear. */
	.band {
		display: grid;
		grid-template-columns: var(--cells, repeat(auto-fit, minmax(0, 1fr)));
		border-top: var(--rule);
	}

	.band > * {
		padding: var(--divide) var(--pad);
	}

	.band > * + * {
		border-left: var(--rule);
	}

	.band.nested {
		padding: 0;
		border-top: 0;
	}

	/* Out to the section's own edges, which is where a band's rules have to end,
	   and down to the bottom one, which the section's padding would otherwise hold
	   it off. */
	.bleed {
		margin-inline: calc(-1 * var(--pad));
		margin-bottom: calc(-1 * var(--pad));
	}

	/* A whole band of headline readings rather than one beside a chart: they line
	   up on their centres, since there is nothing in the cell to range against. */
	.centred > * {
		display: grid;
		gap: 0.55rem;
		justify-items: center;
		text-align: center;
	}

	.centred strong {
		display: flex;
		align-items: center;
		gap: 0.55rem;
		color: var(--mint);
		font-family: var(--font-mono);
		font-size: 1.15rem;
		text-transform: uppercase;
	}

	/* The dot only agrees with the word beside it — it is never the only thing
	   saying which way this reads. */
	.centred i {
		width: 0.4rem;
		height: 0.4rem;
		border-radius: 50%;
		background: currentcolor;
	}

	.centred .down {
		color: var(--coral);
	}

	.centred .unknown {
		color: var(--text-faint);
	}

	/* Eight lanes have to divide this and still each be a lane, so it is taller than
	   the readings beside it. */
	.offsets {
		--graph-min: 13rem;
	}

	/* Wall to wall along the foot of the section: a trace this wide is read across,
	   and the height only has to be enough to see the line move. */
	.history {
		--graph-min: 10rem;
	}

	.offset-chart {
		min-height: var(--graph-min);
	}

	.sync {
		display: grid;
		gap: var(--divide);
		align-content: start;
	}

	.sync .figure {
		display: flex;
		align-items: center;
		gap: 0.6rem;
		color: var(--mint);
		text-transform: uppercase;
	}

	.sync .down {
		color: var(--coral);
	}

	.stale {
		margin: 0.35rem 0 0;
		color: var(--coral);
	}

	/* Name, reading, and the dots that carry the eye between them. */
	.leaders {
		display: grid;
		gap: 0.6rem;
		margin: 0;
	}

	.leaders div {
		display: grid;
		grid-template-columns: auto minmax(1rem, 1fr) auto;
		gap: 0.5rem;
		align-items: baseline;
	}

	.leaders i {
		height: 1px;
		color: var(--color-border);
		background-image: var(--dot-row);
		transform: translateY(-0.15em);
	}

	.leaders dd {
		margin: 0;
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.7rem;
	}


	/* The io map wants a wider gutter than the graphs above it: these row labels are
	   words, not core numbers. Taller too — four lanes divide the block, so the floor
	   has to leave each one a cell worth looking at. */
	.io {
		--axis-w: 5rem;
		--graph-min: 8rem;
	}

	/* A section that is nothing but bands, stacked. It starts against the rule under
	   the heading rather than a gap below it, so the first band brings no rule of
	   its own. */
	.bands {
		--graph-min: 12rem;

		margin-top: calc(-1 * var(--divide));
	}

	.bands > .band:first-child {
		border-top: 0;
	}

	.quality {
		--graph-min: 6rem;
	}

	.quality .nested > div {
		display: flex;
		flex-direction: column;
		gap: 0.45rem;
	}

	.quality strong,
	.latency-reading strong {
		color: var(--mint);
		font-family: var(--font-mono);
		font-size: 1.45rem;
	}

	.quality small,
	.latency-reading span {
		color: var(--text-faint);
		font-family: var(--font-mono);
		font-size: 0.6rem;
	}

	.latency-reading {
		display: flex;
		align-items: baseline;
		gap: 1.25rem;
	}

	.latency-reading strong {
		color: var(--violet);
	}

	/* Under this the rail cannot hold its column and its labels at once. It goes
	   horizontal along the top instead, still sticky, still the way through the
	   page. */
	@media (max-width: 52rem) {
		.server {
			grid-template-columns: minmax(0, 1fr);
			gap: 1rem;
			/* One column, nothing to divide. */
			background: none;
		}

		.rail {
			z-index: 2;
			flex-direction: row;
			align-items: center;
			gap: 1rem;
			max-height: none;
			padding: 0.5rem 0;
			border-bottom: 1px solid var(--color-border);
			background: var(--color-background);
		}

		.rail-art,
		.rail-foot {
			display: none;
		}

		nav {
			flex-direction: row;
			gap: 1.25rem;
			overflow-x: auto;
		}

		nav a {
			padding: 0.25rem 0;
			white-space: nowrap;
		}

		.stack {
			--graph-min: 5rem;
		}

		/* The split cannot hold two columns either: everything stacks, so the rule
		   between the columns lies down with them. */
		.split {
			grid-template-columns: minmax(0, 1fr);
		}

		.beside {
			margin-top: 0;
			margin-inline: calc(-1 * var(--pad));
			padding-left: var(--pad);
			padding-right: var(--pad);
			padding-top: var(--divide);
			border-left: 0;
			border-top: var(--rule);
		}

		/* No band holds its cells side by side at this width: they stack, and the
		   rule between them lies down with them. The four counts are the exception —
		   they are short enough to stay a row. */
		.band:not(.nested) {
			grid-template-columns: minmax(0, 1fr);
		}

		.band:not(.nested) > * + * {
			border-top: var(--rule);
			border-left: 0;
		}
	}
</style>
