<script>
	// Generated by ../asciiArt from the source photographs there.
	import AsciiDish from '$lib/components/AsciiDish.svelte';
	import AsciiShip from '$lib/components/AsciiShip.svelte';
	import Capacity from '$lib/components/Capacity.svelte';
	import Dashboard from '$lib/components/Dashboard.svelte';
	import Dial from '$lib/components/Dial.svelte';
	import Heatmap from '$lib/components/Heatmap.svelte';
	import Horizon from '$lib/components/Horizon.svelte';
	import MetricRow from '$lib/components/MetricRow.svelte';
	import Panel from '$lib/components/Panel.svelte';
	import Placeholder from '$lib/components/Placeholder.svelte';
	import Spark from '$lib/components/Spark.svelte';
	import Spread from '$lib/components/Spread.svelte';
	import Stack from '$lib/components/Stack.svelte';
	import Trace from '$lib/components/Trace.svelte';
	import {
		bytes,
		clockPosition,
		degrees,
		duration,
		microseconds,
		microspan,
		pct,
		ppm,
		rate,
		stamp
	} from '$lib/format.js';
	import { fleet } from '$lib/containers.js';
	import { memoryBands } from '$lib/memory.js';
	import { RANGE, server, watch } from '$lib/server.svelte.js';
	import { bucket, last, mean, outages, summarise } from '$lib/stats.js';
	import { volume } from '$lib/storage.js';
	import { spread } from '$lib/time.js';

	/* Wireframe. CPU and storage are wired up; everything else is a placeholder
	   holding the shape of what goes there. One entry per section of the page and
	   per stop on the rail: a section is a box on the page, its own heading, and
	   its own place in the list. */
	const SECTIONS = [
		{ id: 'overview', label: 'Overview' },
		{ id: 'cpu', label: 'CPU' },
		{ id: 'memory', label: 'Memory' },
		{ id: 'storage', label: 'Storage' },
		{ id: 'network', label: 'Network' },
		{ id: 'time', label: 'Time' },
		{ id: 'containers', label: 'Containers' }
	];

	/* The two drives. One entry each: the id is the prefix every one of their
	   series is named with, and the tone is theirs wherever they appear — capacity
	   box, horizon, io lane. */
	const DISKS = [
		{ id: 'nvme', label: 'NVMe', tone: 'var(--violet)' },
		{ id: 'ssd', label: 'SSD', tone: 'var(--azure)' }
	];

	/* Columns in the heatmaps. The series is 24h at five-minute steps, so this is
	   about a quarter-hour a cell — fine enough to see a spike, coarse enough that
	   a cell is still a cell rather than a hairline. */
	const HEAT_COLUMNS = 72;

	$effect(watch);

	let snapshot = $derived(server.snapshot);
	let series = $derived(server.series);
	let month = $derived(server.month);

	/* How the machine's memory is divided, as three shares of the whole. */
	let ram = $derived(memoryBands(series));

	/* Each volume worked out from its own 30-day series: where it is, which way it
	   is going, and when that runs out. The capacity boxes and the horizon are the
	   same objects seen two ways. */
	let volumes = $derived(
		DISKS.map((disk) =>
			volume({
				...disk,
				used: month?.[`${disk.id}UsedBytes`],
				available: month?.[`${disk.id}AvailableBytes`],
				percent: month?.[`${disk.id}Percent`]
			})
		)
	);

	/* The live reading, written the way $lib/format.js writes that quantity — the
	   same spelling the stats and the map key beside it use, so one number is not
	   quoted to two precisions in one box. */
	const reading = (key, format) => format(snapshot?.[key]);

	/* Read and write on each disk, a lane of the pulse map each. The two sit orders
	   of magnitude apart on the same drive, so the map normalises per row — a lane
	   says when that stream was busy, not how it compares to the one under it. The
	   current rate is on the right of each lane for that. */
	let io = $derived(
		DISKS.flatMap(({ id, label, tone }) =>
			['Read', 'Write'].map((direction) => {
				const points = series?.[`${id}${direction}BytesPerSecond`];
				return {
					id: `${label} ${direction.toLowerCase()}`,
					group: label,
					tone,
					now: rate(last(points)),
					cells: bucket(points, HEAT_COLUMNS)
				};
			})
		).filter((lane) => lane.cells.length)
	);

	/* Per-core utilisation as a map: one row a core, one cell a bucket, straight
	   off the same 0-100% scale the traces are drawn against. */
	let cores = $derived(
		Object.entries(series?.cpuPerCorePercent ?? {})
			.sort(([a], [b]) => Number(a) - Number(b))
			.map(([id, points]) => ({
				id: `C${id}`,
				now: pct(last(points)),
				cells: bucket(points, HEAT_COLUMNS)
			}))
	);

	let rx = $derived(series?.networkReceiveBytesPerSecond ?? []);
	let tx = $derived(series?.networkTransmitBytesPerSecond ?? []);
	const ms = (v) => (Number.isFinite(v) ? `${Math.round(v)} ms` : '—');

	/* Availability is read in nines, so it keeps two decimals where pct() would
	   round 99.98% up to a month without an outage in it. */
	const nines = (v) => (Number.isFinite(v) ? `${v.toFixed(2)}%` : '—');

	/* The status series is 1 for a poll the machine answered and 0 for one it did
	   not, so its mean is the share of the window the machine was up.

	   Read off the 24h series and not the 30d one, even though a month is the
	   window worth quoting: the API downsamples the long range to two-hour steps
	   and does not carry the failures through, so every one of its readings is
	   exactly 1 and an outage that plainly happened is not in it. A number that
	   cannot go below 100% is not an availability figure. */
	let statusDay = $derived(series?.status ?? []);
	let availability = $derived(statusDay.length ? mean(statusDay.map((p) => p[1])) * 100 : null);
	let incidents = $derived(outages(statusDay));

	let online = $derived(snapshot?.server === 'online');

	/* The clock, and every source it listens to as a reading with a bound. */
	let clock = $derived(snapshot?.time);
	let offsets = $derived(spread(clock));

	/* Chrony reports the correction needed to reach NTP: a negative correction
	   means this machine is fast. Flip it here so positive reads naturally as
	   PHOBOS ahead and negative as PHOBOS behind. */
	let clockHistory = $derived(
		(series?.timeSystemOffsetSeconds ?? []).map(([time, offset]) => [time, -offset])
	);
	let currentClockOffset = $derived(
		Number.isFinite(clock?.systemOffsetSeconds) ? -clock.systemOffsetSeconds : null
	);
	let clockLimit = $derived.by(() => {
		const greatest = Math.max(50e-6, ...clockHistory.map((point) => Math.abs(point[1])));
		return Math.ceil((greatest * 1.15) / 50e-6) * 50e-6;
	});
	/* The containers as the fleet and its slots, both already written out. */
	let containerFleet = $derived(fleet(snapshot?.containers));

	/* The fuller of the two drives, which is the one an overview has room to name:
	   the disk worth pointing at is the one that runs out first. */
	let disk = $derived(volumes.reduce((a, b) => ((b.percentNow ?? -1) > (a.percentNow ?? -1) ? b : a)));

	/* Whether all is well, in a sentence. The word carrying the verdict is held
	   apart from the rest of it because that word is the one that takes the colour
	   — the sentence still says which way it reads with the colour gone. */
	let health = $derived.by(() => {
		if (!snapshot)
			return { word: 'Waiting', rest: 'on the machine', note: 'Nothing has come back yet.' };

		if (!online)
			return {
				word: 'No',
				rest: 'answer from the server',
				tone: 'var(--coral)',
				note: 'The probe is not getting a reply. Everything below is the last reading that came back, not what is true now.'
			};

		if (containerFleet.unhealthy)
			return {
				word: `${containerFleet.unhealthy}`,
				rest: containerFleet.unhealthy === 1 ? 'container unhealthy' : 'containers unhealthy',
				tone: 'var(--amber)',
				note: 'The machine itself is answering and its own readings are in band. The containers section has which one, and what it is doing.'
			};

		return {
			word: 'All',
			rest: 'systems operational',
			tone: 'var(--mint)',
			note: 'The server is answering, every container is up, and every reading below is inside the band it is normally in.'
		};
	});

	/* The dashboard in one row: each section's headline reading, what it is
	   measured against, and the window behind it where there is one to draw. The
	   figures are the ones their own sections carry — the same numbers, smaller,
	   so the head of the page is a summary rather than a second source. */
	let tiles = $derived([
		{
			label: 'Uptime',
			value: online ? duration(snapshot.uptimeSeconds) : 'Down',
			detail: online ? 'Since last restart' : 'Not answering',
			tone: online ? 'var(--mint)' : 'var(--coral)',
			/* Up is 1 and down is 0, so the trace is a flat line at the top with a
			   notch cut out of it wherever a poll went unanswered. Unshaded: a line
			   along the top of its box would otherwise fill the box. */
			points: statusDay,
			domain: [0, 1],
			fill: false
		},
		{
			label: 'Availability',
			value: nines(availability),
			detail: `${RANGE} rolling`,
			tone: 'var(--mint)'
		},
		{
			label: 'Incidents',
			value: statusDay.length ? incidents : '—',
			detail: `Last ${RANGE}`,
			tone: incidents > 0 ? 'var(--coral)' : 'var(--mint)'
		},
		{
			label: 'Planned outage',
			/* Nothing scheduled is not a reading in the same sense as the rest, and is
			   set back so it does not read as one. */
			value: '—',
			detail: 'None scheduled',
			tone: 'var(--text-faint)'
		},
		{
			label: 'CPU',
			value: reading('cpuPercent', pct),
			detail: reading('cpuTemperatureC', degrees),
			tone: 'var(--mint)',
			points: series?.cpuPercent,
			domain: [0, 100]
		},
		{
			label: 'Memory',
			value: reading('memoryPercent', pct),
			detail: snapshot
				? `${bytes(snapshot.memoryUsedBytes)} / ${bytes(snapshot.memoryTotalBytes)}`
				: '—',
			tone: 'var(--violet)',
			points: series?.memoryUsedBytes
		},
		{
			label: 'Storage',
			value: pct(disk.percentNow),
			detail: disk.totalNow ? `${disk.label} ${bytes(disk.usedNow)} / ${bytes(disk.totalNow)}` : '—',
			tone: disk.tone,
			/* The 30d series it was worked out from: used space moves over weeks, and
			   a day of it is a flat line. */
			points: disk.points
		},
		{
			label: 'Latency',
			value: reading('latencyMs', ms),
			detail: `P95 ${summarise(series?.latencyMs, ms)[2][1]}`,
			tone: 'var(--azure)',
			points: series?.latencyMs
		},
		{
			label: 'Containers',
			value: containerFleet.running,
			detail: containerFleet.unhealthy ? `${containerFleet.unhealthy} unhealthy` : 'All healthy',
			tone: containerFleet.unhealthy ? 'var(--coral)' : 'var(--mint)'
		}
	]);
</script>

<svelte:head>
	<title>Server — Joshua Smith</title>
</svelte:head>

{#snippet stub(label, note, lines)}
	<Panel {label}>
		<Placeholder {note} {lines} />
	</Panel>
{/snippet}

{#snippet overview()}
	<!-- The verdict, standing on the machine it is about: the art is a picture
	     rather than a chart, so the notice is laid over the empty half of it
	     instead of being given a box beside it. Decorative — the section is named
	     by its heading, and the art is thousands of digits to a screen reader. -->
	<div class="notify">
		<div class="art dish" aria-hidden="true"><AsciiDish /></div>

		<div class="notice" style:color={health.tone}>
			<p class="verdict">
				<i class="mark" aria-hidden="true"></i><strong>{health.word}</strong>
				<span>{health.rest}</span>
			</p>
			<p class="note">{health.note}</p>
		</div>
	</div>

	<!-- Every section of the page in one reading each, in the order they come. -->
	<div class="tiles bleed">
		{#each tiles as tile (tile.label)}
			<div class="tile">
				<Panel label={tile.label}>
					<strong>{tile.value}</strong>
					<span class="detail">{tile.detail}</span>
					<Spark points={tile.points} domain={tile.domain} tone={tile.tone} fill={tile.fill ?? true} />
				</Panel>
			</div>
		{/each}
	</div>
{/snippet}

{#snippet cpu()}
	<div class="stack">
		<MetricRow
			label="Usage"
			value={reading('cpuPercent', pct)}
			tone="var(--mint)"
			stats={summarise(series?.cpuPercent, pct)}
		>
			<!-- The key spells out the band the colours cover, since the map is
			     stretched to the range the cores actually ran at. -->
			<Heatmap rows={cores} format={pct} note="no per-core history yet" />
		</MetricRow>

		<MetricRow
			label="Pressure"
			value={reading('cpuPressurePercent', pct)}
			tone="var(--coral)"
			stats={summarise(series?.cpuPressurePercent, pct)}
		>
			<!-- Sustained pressure is the reading that matters rather than any one
			     spike, so the rules are the two levels worth seeing a trace cross. -->
			<Trace
				lines={[{ id: 'pressure', points: series?.cpuPressurePercent, tone: 'var(--coral)' }]}
				domain={[0, 100]}
				format={pct}
				marks={[25, 50]}
			/>
		</MetricRow>

		<MetricRow
			label="Temperature"
			value={reading('cpuTemperatureC', degrees)}
			tone="var(--amber)"
			stats={summarise(series?.cpuTemperatureC, degrees)}
		>
			<!-- Not zero-based like the other two: nothing here runs near an ambient
			     0°C, so the bottom 40° of the axis would be empty and the trace flat
			     against the top of it. -->
			<Trace
				lines={[{ id: 'temperature', points: series?.cpuTemperatureC, tone: 'var(--amber)' }]}
				domain={[40, 100]}
				format={degrees}
				marks={[60, 80]}
			/>
		</MetricRow>
	</div>
{/snippet}

{#snippet memory()}
	<div class="bleed bands memory">
		<div class="band" style="--cells: minmax(0, 1fr) minmax(0, 2fr)">
			<Dial
				label="RAM usage"
				percent={snapshot?.memoryPercent}
				tone="var(--mint)"
				detail={snapshot
					? `${bytes(snapshot.memoryUsedBytes)} / ${bytes(snapshot.memoryTotalBytes)}`
					: '—'}
			/>

			<Panel label="Memory history">
				<!-- Used, cache and free, which is how the memory is actually divided: the
				     cache is the part the machine would give back under pressure. -->
				<Stack bands={ram} note="no memory history yet" />
			</Panel>
		</div>

		<div class="band pressure">
			<Panel label="Pressure">
				<!-- No domain: this reading lives in hundredths of a percent, so the scale
				     is the range it covered rather than the 0-100 a share could take.
				     Some is any task waiting on memory, full is every task waiting at
				     once — the second is the one that means the machine stopped. -->
				<Trace
					lines={[
						{ id: 'some', points: series?.memoryPressureSomePercent, tone: 'var(--amber)', label: 'Some' },
						{ id: 'full', points: series?.memoryPressureFullPercent, tone: 'var(--coral)', label: 'Full', dashed: true }
					]}
					format={pct}
				/>
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet storage()}
	<!-- The volumes take the first third; the horizon takes the rest, because it is
	     the one chart that reads them together. Everything else about the disks runs
	     along the bottom. -->
	<div class="bleed bands">
		<div class="band" style="--cells: minmax(0, 1fr) minmax(0, 2fr)">
			<div class="stack">
				{#each volumes as vol (vol.id)}
					<!-- The series' last percent, or the live snapshot's until the history
					     has one: the reading is the same either way. -->
					<Capacity
						label="{vol.label} capacity"
						percent={vol.percentNow ?? snapshot?.[`${vol.id}Percent`]}
						tone={vol.tone}
						detail={vol.totalNow ? `${bytes(vol.usedNow)} / ${bytes(vol.totalNow)}` : '—'}
					/>
				{/each}
			</div>

			<Horizon {volumes} />
		</div>

		<div class="band io">
			<Panel label="I/O pulse">
				<!-- Each lane is stretched to its own busiest quarter-hour, so the key
				     quotes that lane's own floor and ceiling in bytes a second. -->
				<Heatmap rows={io} normalise="row" format={rate} note="no io history yet" />
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet network()}
	<!-- Two bands across the section rather than a grid of panels: the throughput
	     and what is left of the link on top, the counts and the probe under it. -->
	<div class="bleed bands">
		<div class="band" style="--cells: minmax(0, 3fr) minmax(10rem, 1fr)">
			<Panel label="Throughput">
				<Trace
					lines={[
						{ id: 'rx', points: rx, tone: 'var(--azure)', label: 'RX' },
						{ id: 'tx', points: tx, tone: 'var(--violet)', label: 'TX' }
					]}
					format={rate}
				/>
			</Panel>

			<Dial
				label="Network utilisation"
				percent={snapshot?.networkUtilizationPercent}
				tone="var(--azure)"
				detail={`${rate(Math.max(snapshot?.networkReceiveBytesPerSecond ?? 0, snapshot?.networkTransmitBytesPerSecond ?? 0))} / ${rate(snapshot?.networkLinkSpeedBytes)}`}
			/>
		</div>

		<!-- One band of four rather than three nested beside one: the counts are
		     peers of the probe, not a group set against it, and the extra level of
		     division was costing each count the width its name needs. The probe
		     takes half again, since it carries a chart and they carry a number. -->
		<div class="band quality" style="--cells: repeat(3, minmax(0, 1fr)) minmax(0, 1.6fr)">
			<!-- Both directions to a count, the way the errors beside them already
			     read: a packet lost on the way out is the same fault as one lost on
			     the way in, and which end it happened at is not something this box
			     can act on. -->
			{#each [
				['Drops', snapshot ? snapshot.networkReceiveDropsPerSecond + snapshot.networkTransmitDropsPerSecond : null],
				['Errors', snapshot ? snapshot.networkReceiveErrorsPerSecond + snapshot.networkTransmitErrorsPerSecond : null],
				['TCP retransmits', snapshot?.networkTcpRetransmitsPerSecond]
			] as [label, value] (label)}
				<Panel {label}>
					<!-- Rounded: these are counts a second, and summing two of them is
					     what turns 0.1 and 0.2 into 0.30000000000000004. The unit sits on
					     the figure's own baseline: it is part of the reading, not a line
					     under it. -->
					<p class="rate">
						<strong>{Number.isFinite(value) ? +value.toFixed(2) : '—'}</strong><small>/s</small>
					</p>
				</Panel>
			{/each}

			<Panel label="HTTP probe latency">
				<p class="latency-reading">
					<strong>{reading('latencyMs', ms)}</strong><span>P95 {summarise(series?.latencyMs, ms)[2][1]}</span>
				</p>
				<Trace lines={[{ id: 'latency', points: series?.latencyMs, tone: 'var(--azure)' }]} format={ms} />
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet time()}
	<div class="bleed bands">
		<div class="band" style="--cells: minmax(0, 2.2fr) minmax(13rem, 1fr)">
			<Panel label="Source offsets">
				<!-- The bar is what each source admits it could be wrong by, so a short
				     one is a source worth following. They agree on the offset to a
				     fraction of a millisecond and differ sevenfold on their confidence,
				     which is the whole reading. -->
				<Spread rows={offsets} format={microseconds} note="no time sources reported" />
			</Panel>

			<div class="sync">
				<Panel label="Sync status">
					<strong class="figure" class:down={!clock?.synchronized}>
						{clock?.synchronized ? clockPosition(currentClockOffset) : 'Not synchronised'}
					</strong>
					{#if clock?.stale}
						<p class="eyebrow stale">Reading is stale</p>
					{/if}
				</Panel>

				<dl class="leaders">
					{#each [
						['RMS offset', microspan(clock?.rmsOffsetSeconds)],
						['Root delay', microspan(clock?.rootDelaySeconds)],
						['Root dispersion', microspan(clock?.rootDispersionSeconds)],
						['Frequency', ppm(clock?.frequencyPpm)],
						['Stratum', clock?.stratum ?? '—'],
						['Leap status', clock?.leapStatus ?? '—']
					] as [name, value] (name)}
						<!-- The filler is the dotted rule the rest of the page measures with,
						     run between the name and its reading. -->
						<div><dt class="eyebrow">{name}</dt><i></i><dd>{value}</dd></div>
					{/each}
				</dl>
			</div>
		</div>

		<div class="band history">
			<Panel label="Offset">
				<Trace
					lines={[{ id: 'offset', points: clockHistory, tone: 'var(--azure)', area: false }]}
					domain={[-clockLimit, clockLimit]}
					marks={[0]}
					format={microseconds}
				/>
			</Panel>
		</div>
	</div>
{/snippet}

{#snippet containers()}
	<!-- Decorative: the section is named by its heading, and the art is thousands
	     of digits to a screen reader. -->
	<div class="art ship" aria-hidden="true"><AsciiShip /></div>
	{#if containerFleet.slots.length}
		<div class="container-shell bleed">
			<div class="band nested container-summary" style="--cells: repeat(3, minmax(0, 1fr))">
				<div><strong>{containerFleet.running}</strong><span class="eyebrow">Running</span></div>
				<div class:warning={containerFleet.unhealthy > 0}><strong>{containerFleet.unhealthy}</strong><span class="eyebrow">Unhealthy</span></div>
				<div><strong>{containerFleet.memory}</strong><span class="eyebrow">In use</span></div>
			</div>

			<!-- One row a container, one column a reading: the names of the readings
			     are the header, so no row has to repeat them. Scrolls sideways rather
			     than reflowing, because a row read across is the whole point of it. -->
			<div class="fleet">
				<table>
					<thead>
						<tr>
							{#each ['Container', 'Status', 'CPU', 'CPU limit', 'Memory', 'Memory limit', 'Uptime'] as column (column)}
								<th class="eyebrow" scope="col">{column}</th>
							{/each}
						</tr>
					</thead>

					<tbody>
						{#each containerFleet.slots as slot (slot.name)}
							<tr>
								<!-- The name docker knows it by, set as the literal it is. -->
								<th class="name" scope="row">{slot.name}</th>
								<td class="state" class:warning={!slot.healthy}>
									<i aria-hidden="true"></i>{slot.status}
								</td>

								<!-- What it is using of what it was given, in that resource's own
								     colour: the reading with the share it comes to under it, then
								     the allowance that share is measured against. -->
								{#each slot.resources as resource (resource.id)}
									<td class="usage" style:color={resource.tone}>
										{resource.value}
										<i class="resource-bar"><i style:width="{resource.fill}%"></i></i>
									</td>
									<td class="limit">{resource.limit}</td>
								{/each}

								<td>{slot.uptime}</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		</div>
	{:else}
		<Placeholder note="no container data" lines={3} />
	{/if}
{/snippet}

<Dashboard title="Server" sections={SECTIONS} max="none">
	<!-- Each section's body is the snippet named after it. -->
	{#snippet body(section)}
		{@render { overview, cpu, memory, storage, network, time, containers }[section.id]()}
	{/snippet}

	{#snippet foot()}
		<span class="eyebrow">Last updated</span>
		<!-- The stamp the snapshot came with, not the clock: this says how fresh
		     the numbers above are, which is not the same as what time it is. -->
		<span class="mono">{stamp(snapshot?.generatedAt)}</span>
	{/snippet}
</Dashboard>

<style>
	.mono {
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.72rem;
	}

	/* A piece of generated ascii art. A character grid has one size — how big one
	   cell is — so the art is sized by setting that from the box it sits in, and
	   --cols is how many cells wide the grid measures: its column count times the
	   0.6021em JetBrains Mono advances per character. Every piece on this page
	   therefore spans its box and shrinks with it. */
	.art {
		container-type: inline-size;
	}

	.art :global(pre) {
		font-size: calc(100cqw / var(--cols));
		/* The generator sets line-height 0.72, which at these sizes lands between
		   pixels (9.55 x 0.72 = 6.88). Painting rounds each row's baseline on its
		   own, so a fractional pitch comes out as a 7, 7, 7, 6 rhythm: every fourth
		   row sits a pixel tight against the one above and the collisions read as
		   horizontal bands across the picture. Rounding the pitch to something a row
		   can be painted at makes every row the same height instead.

		   This is a ratio of the font size, not a fixed height, so it tracks the art
		   as it scales with its container. What it costs is the rounding: the rows
		   are up to half a device pixel off the 0.72, which is under 3% of the
		   picture's height wherever a digit in it is legible. */
		line-height: round(0.72em, var(--device-px, 1px));
	}

	/* 166 columns, which at the width of a section box is the ~9.5px the bull's own
	   digits are set at on a laptop screen. This is the cell size, not a count of
	   what is in any one picture: every piece that heads a section is scaled by it,
	   so a digit is one size across the page whether that art turns out to be 164
	   columns or 166. */
	.dish,
	.ship {
		--cols: 99.95;
	}

	/* A grid of stubs follows it; the foot under the dish brings its own air. */
	.ship {
		margin-bottom: 0.75rem;
	}

	/* The picture runs out to the section's right edge and takes the right of the
	   frame; the notice is laid over the left of it, which is sky. */
	.notify {
		position: relative;
		margin-right: calc(-1 * var(--pad));
	}

	/* A picture is as tall as its width, and this one heads a band rather than
	   filling one: capped, or a wide window turns the head of the page into a
	   poster of a satellite dish. */
	.notify .art {
		width: min(55%, 44rem);
		margin-left: auto;
	}

	.notice {
		position: absolute;
		top: 0;
		left: 0;
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		/* Short of the dish at every width the art is drawn at. */
		max-width: min(34rem, 55%);
	}

	/* The verdict in the section's own colour, the sentence it is part of in the
	   page's: the reading is one word and the rest is what it is about. */
	.verdict {
		margin: 0;
		font-size: clamp(1.2rem, 2.1vw, 1.85rem);
		font-weight: 600;
		letter-spacing: -0.01em;
	}

	.verdict span {
		color: var(--color-foreground);
	}

	/* The same lit dot the rail marks the section you are in with. */
	.mark {
		display: inline-block;
		width: 0.6em;
		height: 0.6em;
		margin-right: 0.45em;
		border-radius: 50%;
		background: currentcolor;
		box-shadow: 0 0 0.75em currentcolor;
	}

	.note {
		margin: 0;
		max-width: 46ch;
		color: var(--text-dim);
		font-size: 0.82rem;
		line-height: 1.55;
	}

	/* One reading per section along the foot of the box. The lattice between them
	   is the grid's own gaps over the rule's colour rather than a border on each
	   cell: at a width that cannot hold nine of them the row wraps, and lines drawn
	   this way still meet wherever the cells land. */
	.tiles {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(7.5rem, 1fr));
		gap: 1px;
		border-top: var(--rule);
		background: var(--rule-color);
	}

	.tile {
		/* Shallower traces than the cards on the landing page: this is a row of
		   nine, not three across the width of the bull. */
		--spark: 1.4rem;

		display: grid;
		padding: var(--divide) 1rem;
		background: var(--surface);
	}

	/* The outermost cells keep the section's own padding, so the labels down the
	   left of the page all start on one line. */
	.tile:first-child {
		padding-left: var(--pad);
	}

	.tile:last-child {
		padding-right: var(--pad);
	}

	.tile strong {
		color: var(--color-foreground);
		font-family: var(--font-mono);
		font-size: 1.15rem;
	}

	.tile .detail {
		margin-bottom: 0.35rem;
		color: var(--text-dim);
		font-size: 0.68rem;
	}


	.container-shell {
		/* A grid item takes its minimum from its contents, which for a table means
		   the width of the widest row — it would stand the table outside the box
		   rather than let it scroll inside one. */
		min-width: 0;
		margin-inline: calc(-1 * var(--pad));
		border-top: var(--rule);
	}

	/* A row is read across, so it is never broken up to fit: under the width the
	   columns need, the table keeps its shape and the box scrolls. */
	.fleet {
		/* On the box rather than on the table, so it divides the summary from the
		   fleet wall to wall and stays put when the columns scroll under it. */
		border-top: var(--rule);
		overflow-x: auto;
		scrollbar-width: thin;
	}

	.fleet table {
		width: 100%;
		border-collapse: collapse;
		font-family: var(--font-mono);
		font-size: 0.68rem;
	}

	/* Left, like everything else on the page, and never wrapped: a reading broken
	   over two lines stops being one. The gutter is on the right of every cell, and
	   the section's own padding on the two outside ones, so the rules still run wall
	   to wall. */
	.fleet th,
	.fleet td {
		padding: 0.65rem 1.5rem 0.65rem 0;
		font-weight: 400;
		text-align: left;
		white-space: nowrap;
	}

	.fleet tr > :first-child {
		padding-left: var(--pad);
	}

	.fleet tr > :last-child {
		padding-right: var(--pad);
	}

	/* The header names the columns once. It is the one row set in the page's small
	   caps rather than mono: it is a label, not a reading. */
	.fleet thead th {
		padding-top: var(--divide);
		padding-bottom: 0.5rem;
		border-bottom: var(--rule);
	}

	.fleet tbody tr + tr th,
	.fleet tbody tr + tr td {
		border-top: var(--rule);
	}

	.name {
		color: var(--color-foreground);
	}

	/* A square of the state's own colour, and the word beside it — the colour is
	   never the only thing saying which way a row reads. */
	.state {
		color: var(--mint);
		text-transform: capitalize;
	}

	.state i {
		display: inline-block;
		width: 0.45rem;
		height: 0.45rem;
		margin-right: 0.5rem;
		background: currentcolor;
	}

	/* The allowance the reading beside it is drawn against, set back from it: the
	   number that moves is the one worth reading down the column. */
	.limit {
		color: var(--text-dim);
	}

	/* Wide enough that the share under the reading is a bar rather than a mark. */
	.usage {
		min-width: 5rem;
	}

	.container-summary > div {
		display: flex;
		align-items: baseline;
		gap: 0.8rem;
		color: var(--mint);
	}

	.container-summary .eyebrow {
		color: var(--text-dim);
	}

	/* Under the reading, the width of the cell it is in. */
	.resource-bar {
		display: block;
		height: 2px;
		margin-top: 0.4rem;
		background: var(--color-border);
	}

	.resource-bar i {
		display: block;
		height: 100%;
		min-width: 0;
		background: currentcolor;
	}

	/* Both as specific as the rule each is turning off, or the cell keeps the mint
	   it wears when everything is well and a count of unhealthy containers reads
	   as a good number. */
	.container-summary > .warning,
	td.state.warning {
		color: var(--coral);
	}

	/* Taller than a row's sparkline: this chart is three bands deep and the dial
	   beside it is a shape of its own, not a line of text. */
	.memory {
		--graph-min: 9rem;
	}

	/* A chart read across rather than down: the height only has to be enough to see
	   a line move. */
	.pressure {
		--graph-min: 6rem;
	}

	/* Every reading that sits in a band, at one size: these are rows of figures
	   read across and compared down the page, so a cell does not get to pick a
	   size of its own. Mono, unlike the .figure a whole section is known by —
	   these are counts, not headlines. The colour is the band's, since a reading
	   that is off takes its own. */
	.rate strong,
	.latency-reading strong,
	.container-summary strong {
		font-family: var(--font-mono);
		font-size: 1.45rem;
	}

	.rate strong {
		color: var(--mint);
	}

	/* Wall to wall along the foot of the section: a trace this wide is read across,
	   and the height only has to be enough to see the line move. */
	.history {
		--graph-min: 10rem;
	}

	.sync {
		display: grid;
		gap: var(--divide);
		align-content: start;
	}

	.sync .figure {
		display: flex;
		align-items: center;
		gap: 0.6rem;
		color: var(--mint);
		text-transform: uppercase;
	}

	.sync .down {
		color: var(--coral);
	}

	.stale {
		margin: 0.35rem 0 0;
		color: var(--coral);
	}

	/* Name, reading, and the dots that carry the eye between them. */
	.leaders {
		display: grid;
		gap: 0.6rem;
		margin: 0;
	}

	.leaders div {
		display: grid;
		grid-template-columns: auto minmax(1rem, 1fr) auto;
		gap: 0.5rem;
		align-items: baseline;
	}

	.leaders i {
		height: 1px;
		color: var(--color-border);
		background-image: var(--dot-row);
		transform: translateY(-0.15em);
	}

	.leaders dd {
		margin: 0;
		color: var(--text-dim);
		font-family: var(--font-mono);
		font-size: 0.7rem;
	}


	/* The io map wants a wider gutter than the graphs above it: these row labels are
	   words, not core numbers. Taller too — four lanes divide the block, so the floor
	   has to leave each one a cell worth looking at. */
	.io {
		--axis-w: 5rem;
		--graph-min: 8rem;
	}

	/* A section that is nothing but bands, stacked. It starts against the rule under
	   the heading rather than a gap below it, so the first band brings no rule of
	   its own. Tall enough that eight lanes can divide it and each still be a lane,
	   which is the deepest thing any band holds. */
	.bands {
		--graph-min: 13rem;

		margin-top: calc(-1 * var(--divide));
	}

	.bands > .band:first-child {
		border-top: 0;
	}

	.quality {
		--graph-min: 6rem;
	}

	/* The unit belongs to the number, so it sits on its baseline rather than under
	   it. */
	.rate,
	.latency-reading {
		display: flex;
		align-items: baseline;
		gap: 0.3rem;
		margin: 0;
	}

	.latency-reading {
		gap: 1.25rem;
	}

	.rate small,
	.latency-reading span {
		color: var(--text-faint);
		font-family: var(--font-mono);
		font-size: 0.6rem;
	}

	.latency-reading strong {
		color: var(--violet);
	}

	/* Where the shell lays its rail down, the overview gives up its picture: at this
	   width the art is a strip a few characters tall and the notice has nowhere to
	   stand clear of the dish. The words are the part that matters. */
	@media (max-width: 52rem) {
		.notify .art {
			display: none;
		}

		.notice {
			position: static;
			max-width: none;
		}
	}
</style>
