<script>
	// Generated by ../asciiArt: `make site` there rewrites AsciiBull.svelte.
	import AsciiBull from '$lib/components/AsciiBull.svelte';
	import StatusBar from '$lib/components/StatusBar.svelte';
</script>

<svelte:head>
	<title>Joshua Smith — Data Scientist & AI Engineer</title>
</svelte:head>

<div class="landing">
	<div class="wrap">
		<!-- Decorative: the heading below carries the same meaning, and the art is
		     tens of thousands of digits to a screen reader. -->
		<div class="bull" aria-hidden="true">
			<AsciiBull />
		</div>

		<div class="identity">
			<h1>Joshua Smith</h1>
			<p>Data Scientist <span aria-hidden="true">·</span> AI Engineer</p>
		</div>
	</div>

	<StatusBar />
</div>

<style>
	.landing {
		/* --- hero tuning knobs -------------------------------------------
		   --bull-drop: how far the horn tips sit below the header. 0 puts them
		     flush with the bottom of the header; negative pulls them up behind
		     the nav. Plain rem — it is measured outside the zoom below.
		   --bull-scale: the bull's size. This also sets the status bar's width,
		     which is measured from the art rather than declared.
		   Both are the full-size values. The hero is one composition — art, name
		   and status bar share the space under the header — so the queries at
		   the foot of this file only ever step them down, which means whichever
		   axis is tightest wins. */
		--bull-drop: 2rem;
		--bull-scale: 1.6;

		display: grid;
		/* The generator crops the art to its ink bounding box in both axes (see
		   asciiArt src/output.c), so the <pre>'s own box is the horn span: its
		   width is tip to tip, its top edge is the tips themselves. One
		   min-content column sized by the bull hands that exact width to the
		   status bar, and .wrap hangs the top edge off the nav's midline. */
		grid-template-columns: min-content;
		grid-template-rows: minmax(0, 1fr) auto;
		justify-content: center;
		/* Definite height, so the row above the bar is the space that is left
		   rather than however tall the bull happens to be. */
		height: calc(100svh - var(--header-height));
	}

	.wrap {
		position: relative;
		/* The horn tips start exactly where the header ends, so the menu keeps a
		   clear band above them and the bull's bottom tucks that much further
		   into the status bar. align-self keeps this box the art's own height,
		   so the identity can sit at a fixed point on the bull's face. */
		align-self: start;
		margin-top: var(--bull-drop);
	}

	/* The bull dissolves into the page on the way down. This is an overlay of the
	   page colour, not a mask on the art: a mask clips to the element's box, and
	   the top row of glyphs rises above that box — line-height is 0.72, so the
	   first line box is shorter than the glyphs in it — which sliced the tips off
	   the horns. Only works over a flat background, which is what this is. */
	.wrap::after {
		position: absolute;
		inset: 72% 0 -0.5rem;
		background: linear-gradient(to bottom, transparent, var(--color-background) 92%);
		content: '';
		pointer-events: none;
	}

	.bull {
		/* zoom, not transform: scale — zoom scales the layout box too, so the
		   column above measures the art at the size it is actually painted.
		   Keep offsets off this element: zoom would multiply them. */
		zoom: var(--bull-scale);
	}

	.identity {
		position: absolute;
		/* The eyes sit 44% down the source photo (asciiArt images/bull.jpg), and
		   the art is cropped to its ink, so 44% of this box is the eye line. The
		   name hangs from just under it rather than being centred on the face. */
		top: calc(45% + 0.75rem);
		left: 50%;
		z-index: 1;
		width: min(100vw - 2 * var(--gutter), 90rem);
		text-align: center;
		transform: translateX(-50%);
	}

	/* The art runs straight under the name; this pool of background buys the
	   contrast back without a panel that would read as a box. */
	.identity::before {
		position: absolute;
		inset: -4rem -8rem;
		z-index: -1;
		background: radial-gradient(
			ellipse,
			var(--color-background) 0%,
			color-mix(in srgb, var(--color-background) 62%, transparent) 48%,
			transparent 78%
		);
		content: '';
		pointer-events: none;
	}

	h1 {
		margin: 0;
		color: var(--color-foreground);
		/* Sized off whichever axis is scarcer. A wide, short window is the case
		   that bites: 8vw alone puts a 150px name on a 500px-tall screen and it
		   runs straight into the status bar. */
		font-size: clamp(3rem, min(8vw, 14svh), 8rem);
		font-weight: 700;
		letter-spacing: -0.055em;
		line-height: 0.95;
	}

	p {
		/* The gap under the name. Scales with the viewport so it stays in
		   proportion to a heading that is itself sized off vw. */
		margin: clamp(0.65rem, 1.3vw, 1.15rem) 0 0;
		color: var(--color-foreground);
		font-size: clamp(0.78rem, 1.35vw, 1.2rem);
		font-weight: 500;
		letter-spacing: 0.28em;
		text-transform: uppercase;
	}

	p span {
		color: var(--mint);
	}

	@media (max-width: 48rem) {
		.landing {
			--bull-scale: 1.3;
		}

		.identity::before {
			inset-inline: -1rem;
		}

		p {
			letter-spacing: 0.16em;
		}
	}

	/* Short viewports: a laptop at 768, a half-height window, a landscape phone.
	   The header and the status bar cost the same there as they do anywhere, and
	   the name hangs off the art's own height, so the art is what has to give or
	   the name lands on top of the bar. Each step is sized to still clear it at
	   the shortest viewport that step covers, measured at the widest — the name
	   is largest there, so that is the worst case. */
	@media (max-height: 52rem) {
		.landing {
			--bull-scale: 1.3;
			--bull-drop: 1.5rem;
		}
	}

	@media (max-height: 48rem) {
		.landing {
			--bull-scale: 1.05;
			--bull-drop: 1.25rem;
		}
	}

	@media (max-height: 44rem) {
		.landing {
			--bull-scale: 0.78;
			--bull-drop: 1rem;
		}
	}

	/* Past here no size of art leaves the name clear, so the hero stops
	   pretending to fit: it keeps its proportions and the page scrolls the last
	   of it into view. The fold still lands on nav, horns and name. */
	@media (max-height: 40rem) {
		.landing {
			--bull-scale: 0.62;
			--bull-drop: 0.5rem;

			height: auto;
			min-height: calc(100svh - var(--header-height));
		}
	}
</style>
