<script>
	// Generated by ../asciiArt: `make site` there rewrites AsciiBull.svelte.
	import AsciiBull from '$lib/components/AsciiBull.svelte';
	import StatusBar from '$lib/components/StatusBar.svelte';
	/* The rest of the site, which used to be three routes of its own: one scroll
	   now, so the nav is anchors into this page rather than tabs away from it. */
	import About from '$lib/sections/About.svelte';
	import Projects from '$lib/sections/Projects.svelte';
	import Contact from '$lib/sections/Contact.svelte';
</script>

<svelte:head>
	<title>Joshua Smith — Data Engineer</title>
</svelte:head>

<div class="landing" id="home">
	<div class="wrap">
		<!-- Decorative: the heading below carries the same meaning, and the art is
		     tens of thousands of digits to a screen reader. -->
		<div class="bull" aria-hidden="true">
			<AsciiBull />
		</div>

		<div class="identity">
			<h1>Joshua Smith</h1>
			<p class="tagline">I turn numbers into models, decisions and the occasional bull.</p>
			<p class="proof">
				Data Engineer focused on real-time, scientific, and ML systems.
			</p>
			<a
				class="cta"
				href="#projects"
				onclick={() => window.dispatchEvent(new CustomEvent('openproject', { detail: 'ancestree' }))}
				>View my work <span aria-hidden="true">↓</span></a
			>
		</div>
	</div>

	<StatusBar />
</div>

<Projects />
<About />
<Contact />

<style>
	.landing {
		/* --- hero tuning knobs -------------------------------------------
		   The art is a fixed grid of characters — 160 wide, 112 tall — so its
		   whole size is one number: how big one character cell is. Everything
		   here is written in terms of that cell, which is what keeps the
		   composition in proportion instead of being a fixed pixel island that
		   happens to suit one screen. The constants come from measuring the
		   rendered <pre>: JetBrains Mono advances 0.6021em per character and the
		   generated component sets line-height 0.72, so the art is
		     160 x 0.6021 = 96.34 cells wide, 112 x 0.72 = 80.64 cells tall.

		   --art-fill: the share of the viewport height the bull takes. This is
		     the whole look, measured off the reference screenshot — a maximised
		     window on a 16" MacBook Pro, 1728x993 — where the art was 774 tall.
		     774 of 993 is 0.78.
		   --tuck: how far the bull's faded tail runs past the top of the cards.
		     By that point the gradient has taken it to the page colour, so this
		     reads as the bull finishing at the cards rather than short of them.
		   --sky: least clear band between the nav and the horn tips.
		   --bar-reserve: what the cards cost. An estimate, used only to stop the
		     art colliding with them on a short viewport. */
		--art-fill: 0.78;
		--tuck: 4rem;
		--sky: 2rem;
		/* The cards themselves plus the gap they keep from the bottom edge —
		   the same gap every section on the site keeps from the one after it
		   (.page, app.css; StatusBar.svelte's own margin matches it too). */
		--bar-reserve: calc(8.5rem + clamp(0.75rem, 1.5vh, 1.25rem));

		/* Three limits, smallest wins, no breakpoints anywhere: the art may not
		   outgrow the width it is allowed, may not exceed its share of the
		   height, and may never push its top above the sky under the nav. On a
		   normal screen the middle term rules and the composition is the
		   reference one at any size; the outer two take over at the extremes.

		   The floor is the get-out. On a landscape phone or a half-height window
		   the fit term goes to almost nothing and the bull becomes a stamp;
		   below that size the hero stops trying to fit and scrolls instead, which
		   is what the query at the foot of this file allows. It sits inside the
		   width term, never outside it: a floor that could beat the width is a
		   floor that crops the horns off a small phone. */
		--cell: min(
			(100vw - 2 * var(--gutter)) / 96.34,
			max(
				4px,
				min(
					var(--art-fill) * 100svh / 80.64,
					(100svh - var(--header-height) - var(--bar-reserve) + var(--tuck) - var(--sky)) /
						80.64
				)
			)
		);

		display: grid;
		/* The generator crops the art to its ink bounding box in both axes (see
		   asciiArt src/output.c), so the <pre>'s own box is the horn span: its
		   width is tip to tip, its top edge is the tips themselves. One
		   min-content column sized by the bull hands that exact width to the
		   status bar, and .wrap hangs the top edge off the nav's midline. */
		grid-template-columns: min-content;
		grid-template-rows: minmax(0, 1fr) auto;
		justify-content: center;
		/* Definite height, so the row above the bar is the space that is left
		   rather than however tall the bull happens to be. */
		height: calc(100svh - var(--header-height));
	}

	.wrap {
		position: relative;
		/* Centred in what is left between the nav and the cards, so the slack
		   splits evenly above and below instead of collecting under the bull.
		   On a tall portrait screen the art is width-bound and cannot fill the
		   height; dumping all of that at the bottom is what read as a hole
		   between the bull and the cards. align-self keeps this box the art's
		   own height, so the identity can sit at a fixed point on the face. */
		align-self: end;
		margin-bottom: calc(-1 * var(--tuck));
	}

	/* The bull dissolves into the page on the way down. This is an overlay of the
	   page colour, not a mask on the art: a mask clips to the element's box, and
	   the top row of glyphs rises above that box — line-height is 0.72, so the
	   first line box is shorter than the glyphs in it — which sliced the tips off
	   the horns. Only works over a flat background, which is what this is. */
	.wrap::after {
		position: absolute;
		inset: 72% 0 -0.5rem;
		background: linear-gradient(to bottom, transparent, var(--color-background) 92%);
		content: '';
		pointer-events: none;
	}

	/* The generated component hard-codes font-size: 6px. Overriding it here is
	   what actually resizes the art — a character grid has no other size — and
	   it beats the old zoom because the layout box follows natively, so the
	   column above still measures the art at the size it is painted. */
	.bull :global(pre) {
		font-size: var(--cell);
		/* Safari floors a fractional line-height to the nearest CSS pixel on <pre>
		   text (Chrome doesn't), which at this font-size quietly shaved ~13% off
		   every row and left the whole art short — reading as the bull sitting too
		   low under the nav. Rounding to a device pixel ourselves, the same fix
		   already used for every other ascii-art component (see --device-px in
		   app.css), makes both browsers land on the same pixel instead of one of
		   them truncating. */
		line-height: round(0.72em, var(--device-px, 1px));
	}

	.identity {
		position: absolute;
		/* The eyes sit 44% down the source photo (asciiArt images/bull.jpg), and
		   the art is cropped to its ink, so 44% of this box is the eye line. The
		   name hangs from just under it rather than being centred on the face. */
		top: calc(45% + 0.75rem);
		left: 50%;
		z-index: 1;
		width: min(100vw - 2 * var(--gutter), 90rem);
		text-align: center;
		transform: translateX(-50%);
	}

	/* The art runs straight under the name; this pool of background buys the
	   contrast back without a panel that would read as a box. */
	.identity::before {
		position: absolute;
		inset: -4rem -8rem;
		z-index: -1;
		background: radial-gradient(
			ellipse,
			var(--color-background) 0%,
			color-mix(in srgb, var(--color-background) 62%, transparent) 48%,
			transparent 78%
		);
		content: '';
		pointer-events: none;
	}

	/* The name is measured in cells like everything else, so it keeps its size
	   relative to the face it sits on instead of drifting against it. 11 cells
	   is the 105.6px it renders at on the reference screen. The clamps are only
	   end-stops for the extremes the cell cannot sensibly reach. */
	h1 {
		margin: 0;
		color: var(--color-foreground);
		font-size: clamp(1.7rem, 7.6 * var(--cell), 6.2rem);
		font-weight: 700;
		letter-spacing: -0.05em;
		line-height: 0.95;
	}

	/* The only line under the name, and the whole of what this page claims. Sentence
	   case and unstretched, so it reads as something said rather than as a job
	   title — which is the point of it standing here instead of one. Measured in
	   cells like everything else, so the identity still scales as one thing against
	   the face behind it. */
	.tagline {
		margin: clamp(0.6rem, 1.8 * var(--cell), 1.4rem) 0 0;
		color: var(--color-foreground);
		font-size: clamp(0.85rem, 2.5 * var(--cell), 1.75rem);
		font-weight: 400;
		letter-spacing: -0.01em;
		line-height: 1.35;
		text-wrap: balance;
	}

	/* What the line above it is actually claiming, so it is set quieter and to a
	   measure rather than to the box: the identity is as wide as the horns, and a
	   sentence this long run across all of it is not a line anyone reads. Capped in
	   cells like the type itself, so the measure holds its proportion to the face
	   at every size instead of snapping at a breakpoint. */
	.proof {
		max-width: min(100%, 66 * var(--cell));
		margin: clamp(0.5rem, 1.5 * var(--cell), 1.1rem) auto 0;
		color: var(--text-dim);
		font-size: clamp(0.7rem, 1.55 * var(--cell), 1.05rem);
		font-weight: 400;
		line-height: 1.6;
		/* Balanced, not pretty: pretty only guards the last line, which here still
		   left "lightning strikes." alone under two full ones. Centred type wants
		   the whole block evened out. */
		text-wrap: balance;
	}

	/* Sat straight under the line above it, measured in cells like the name so the
	   whole identity block scales as one thing. Otherwise it is the shape every
	   other action on the site wears: mint, mono, small caps, and an arrow that
	   says where it goes — ↓ for further down this page, → for elsewhere on the
	   site, ↗ for off it. */
	.cta {
		display: inline-block;
		margin-top: clamp(0.8rem, 2.2 * var(--cell), 1.6rem);
		color: var(--mint);
		font-family: var(--font-mono);
		font-size: clamp(0.66rem, 1.7 * var(--cell), 1rem);
		font-weight: 500;
		letter-spacing: 0.14em;
		text-decoration: none;
		text-transform: uppercase;
	}

	/* The arrow carries the hover on its own, the way the status bar's link does:
	   the label is already mint, so there is no colour left for it to change to. */
	.cta span {
		display: inline-block;
		transition: transform 160ms ease;
	}

	.cta:hover span,
	.cta:focus-visible span {
		transform: translateY(2px);
	}


	/* The only query left. Everything the old ladder of max-height steps did is
	   now in the three-way min() above, which cannot be caught out by a size
	   nobody thought to test. This one is not about fit: a portrait phone is so
	   much taller than it is wide that a bull kept whole inside the gutter is
	   too small to read as anything, so the horns are allowed off the edges. */
	/* Portrait. Not a size breakpoint — a change of which constraint binds. Past
	   roughly square the art is limited by width, so it cannot reach down to the
	   cards however it is anchored; pinning it to them piles every bit of the
	   slack into one void above the horns. Centring splits that slack instead.
	   The threshold is where the two terms of the min() cross: the art is 1.195
	   cells wide per cell tall, so at --art-fill 0.78 the width term takes over
	   just under square. */
	@media (max-aspect-ratio: 19 / 20) {
		.wrap {
			align-self: center;
			margin-bottom: 0;
		}
	}

	@media (max-width: 48rem) {
		.identity::before {
			inset-inline: -1rem;
		}
	}

	/* Too short for the composition at any size the floor allows, so the hero
	   keeps its proportions and lets the last of itself scroll into view. The
	   fold still lands on nav, horns and name. */
	@media (max-height: 40rem) {
		.landing {
			height: auto;
			min-height: calc(100svh - var(--header-height));
		}
	}
</style>
