<script>
	// Generated by ../asciiArt: `make site` there rewrites AsciiBull.svelte.
	import AsciiBull from '$lib/components/AsciiBull.svelte';
	import StatusBar from '$lib/components/StatusBar.svelte';
</script>

<svelte:head>
	<title>Joshua Smith — Data Scientist & AI Engineer</title>
</svelte:head>

<div class="landing">
	<div class="wrap">
		<!-- Decorative: the heading below carries the same meaning, and the art is
		     tens of thousands of digits to a screen reader. -->
		<div class="bull" aria-hidden="true">
			<AsciiBull />
		</div>

		<div class="identity">
			<h1>Joshua Smith</h1>
			<p>Data Scientist <span aria-hidden="true">·</span> AI Engineer</p>
		</div>
	</div>

	<StatusBar />
</div>

<style>
	.landing {
		/* --- hero tuning knobs -------------------------------------------
		   The art is a fixed grid of characters — 160 wide, 112 tall — so its
		   whole size is one number: how big one character cell is. Everything
		   here is written in terms of that cell, which is what keeps the
		   composition in proportion instead of being a fixed pixel island that
		   happens to suit one screen. The constants come from measuring the
		   rendered <pre>: JetBrains Mono advances 0.6021em per character and the
		   generated component sets line-height 0.72, so the art is
		     160 x 0.6021 = 96.34 cells wide, 112 x 0.72 = 80.64 cells tall.

		   --art-fill: the share of the viewport height the bull takes. This is
		     the whole look, measured off the reference screenshot — a maximised
		     window on a 16" MacBook Pro, 1728x993 — where the art was 774 tall.
		     774 of 993 is 0.78.
		   --tuck: how far the bull's faded tail runs past the top of the cards.
		     By that point the gradient has taken it to the page colour, so this
		     reads as the bull finishing at the cards rather than short of them.
		   --sky: least clear band between the nav and the horn tips.
		   --bar-reserve: what the cards cost. An estimate, used only to stop the
		     art colliding with them on a short viewport. */
		--art-fill: 0.78;
		--tuck: 4rem;
		--sky: 2rem;
		/* The cards themselves plus the gap they keep from the bottom edge,
		   which is the header's own top padding. */
		--bar-reserve: calc(8.5rem + var(--nav-pad-top));

		/* Three limits, smallest wins, no breakpoints anywhere: the art may not
		   outgrow the width it is allowed, may not exceed its share of the
		   height, and may never push its top above the sky under the nav. On a
		   normal screen the middle term rules and the composition is the
		   reference one at any size; the outer two take over at the extremes.

		   The floor is the get-out. On a landscape phone or a half-height window
		   the fit term goes to almost nothing and the bull becomes a stamp;
		   below that size the hero stops trying to fit and scrolls instead, which
		   is what the query at the foot of this file allows. It sits inside the
		   width term, never outside it: a floor that could beat the width is a
		   floor that crops the horns off a small phone. */
		--cell: min(
			(100vw - 2 * var(--gutter)) / 96.34,
			max(
				4px,
				min(
					var(--art-fill) * 100svh / 80.64,
					(100svh - var(--header-height) - var(--bar-reserve) + var(--tuck) - var(--sky)) /
						80.64
				)
			)
		);

		display: grid;
		/* The generator crops the art to its ink bounding box in both axes (see
		   asciiArt src/output.c), so the <pre>'s own box is the horn span: its
		   width is tip to tip, its top edge is the tips themselves. One
		   min-content column sized by the bull hands that exact width to the
		   status bar, and .wrap hangs the top edge off the nav's midline. */
		grid-template-columns: min-content;
		grid-template-rows: minmax(0, 1fr) auto;
		justify-content: center;
		/* Definite height, so the row above the bar is the space that is left
		   rather than however tall the bull happens to be. */
		height: calc(100svh - var(--header-height));
	}

	.wrap {
		position: relative;
		/* Centred in what is left between the nav and the cards, so the slack
		   splits evenly above and below instead of collecting under the bull.
		   On a tall portrait screen the art is width-bound and cannot fill the
		   height; dumping all of that at the bottom is what read as a hole
		   between the bull and the cards. align-self keeps this box the art's
		   own height, so the identity can sit at a fixed point on the face. */
		align-self: end;
		margin-bottom: calc(-1 * var(--tuck));
	}

	/* The bull dissolves into the page on the way down. This is an overlay of the
	   page colour, not a mask on the art: a mask clips to the element's box, and
	   the top row of glyphs rises above that box — line-height is 0.72, so the
	   first line box is shorter than the glyphs in it — which sliced the tips off
	   the horns. Only works over a flat background, which is what this is. */
	.wrap::after {
		position: absolute;
		inset: 72% 0 -0.5rem;
		background: linear-gradient(to bottom, transparent, var(--color-background) 92%);
		content: '';
		pointer-events: none;
	}

	/* The generated component hard-codes font-size: 6px. Overriding it here is
	   what actually resizes the art — a character grid has no other size — and
	   it beats the old zoom because the layout box follows natively, so the
	   column above still measures the art at the size it is painted. */
	.bull :global(pre) {
		font-size: var(--cell);
	}

	.identity {
		position: absolute;
		/* The eyes sit 44% down the source photo (asciiArt images/bull.jpg), and
		   the art is cropped to its ink, so 44% of this box is the eye line. The
		   name hangs from just under it rather than being centred on the face. */
		top: calc(45% + 0.75rem);
		left: 50%;
		z-index: 1;
		width: min(100vw - 2 * var(--gutter), 90rem);
		text-align: center;
		transform: translateX(-50%);
	}

	/* The art runs straight under the name; this pool of background buys the
	   contrast back without a panel that would read as a box. */
	.identity::before {
		position: absolute;
		inset: -4rem -8rem;
		z-index: -1;
		background: radial-gradient(
			ellipse,
			var(--color-background) 0%,
			color-mix(in srgb, var(--color-background) 62%, transparent) 48%,
			transparent 78%
		);
		content: '';
		pointer-events: none;
	}

	/* The name is measured in cells like everything else, so it keeps its size
	   relative to the face it sits on instead of drifting against it. 11 cells
	   is the 105.6px it renders at on the reference screen. The clamps are only
	   end-stops for the extremes the cell cannot sensibly reach. */
	h1 {
		margin: 0;
		color: var(--color-foreground);
		font-size: clamp(2.2rem, 11 * var(--cell), 9rem);
		font-weight: 700;
		letter-spacing: -0.055em;
		line-height: 0.95;
	}

	p {
		margin: clamp(0.6rem, 1.9 * var(--cell), 1.4rem) 0 0;
		color: var(--color-foreground);
		font-size: clamp(0.72rem, 2 * var(--cell), 1.35rem);
		font-weight: 500;
		letter-spacing: 0.28em;
		text-transform: uppercase;
	}

	p span {
		color: var(--mint);
	}

	/* The only query left. Everything the old ladder of max-height steps did is
	   now in the three-way min() above, which cannot be caught out by a size
	   nobody thought to test. This one is not about fit: a portrait phone is so
	   much taller than it is wide that a bull kept whole inside the gutter is
	   too small to read as anything, so the horns are allowed off the edges. */
	/* Portrait. Not a size breakpoint — a change of which constraint binds. Past
	   roughly square the art is limited by width, so it cannot reach down to the
	   cards however it is anchored; pinning it to them piles every bit of the
	   slack into one void above the horns. Centring splits that slack instead.
	   The threshold is where the two terms of the min() cross: the art is 1.195
	   cells wide per cell tall, so at --art-fill 0.78 the width term takes over
	   just under square. */
	@media (max-aspect-ratio: 19 / 20) {
		.wrap {
			align-self: center;
			margin-bottom: 0;
		}
	}

	@media (max-width: 48rem) {
		.identity::before {
			inset-inline: -1rem;
		}

		p {
			letter-spacing: 0.16em;
		}
	}

	/* Too short for the composition at any size the floor allows, so the hero
	   keeps its proportions and lets the last of itself scroll into view. The
	   fold still lands on nav, horns and name. */
	@media (max-height: 40rem) {
		.landing {
			height: auto;
			min-height: calc(100svh - var(--header-height));
		}
	}
</style>
